--- 
title: "Introduction to R for Natural Resource Scientists"
author: "Ben Staton"
date: "with contributions from Henry Hershey"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: bstaton1/au-r-workshop
description: "This is a first course in R Programming for Natural Resource Scientists. It was developed and has been primarily instructed at Auburn University."
---

# Overview{-}

This book is intended to be a first course in R programming for natural resource professionals. It is by no means comprehensive, but instead attempts to introduce the main topics needed to get a beginner up and running with applying R to their own work. It is intended to be a companion to in-person workshop sessions, in which each chapter is covered in a 2 hour session. Although the examples shown have a natural resource/ecological theme, the general skills presented are general to R users across all scientific disciplines. 

## What is Covered? {-}

The book is composed of six chapters intended to cover a suite of topics in introductory R programming. In general, the material builds in complexity from chapter to chapter and earlier chapters can be seen as prerequisites for later chapters. 

*  **Chapter \@ref(ch1)** covers the basics of working in R through RStudio, including the basics of the R coding language and environment.
*  **Chapter \@ref(ch2)** covers the basics of plotting using the base R graphics functionality. 
*  **Chapter \@ref(ch3)** covers the basics of fitting statistical models using built-in functionality for generalized linear models as well as non-linear models.   
*  **Chapter \@ref(ch4)** covers the basics of simulation modeling in R. 
*  **Chapter \@ref(ch5)** covers the basics of the `dplyr` and `reshape2` packages for manipulating and summarizing large data sets using highly readable code.
*  **Chapter \@ref(ch6)** covers the basics of producing maps and performing spatial analysis in R. _This chapter was contributed by Henry Hershey_

## Prerequisites {-}

Chapter \@ref(ch1) starts at the first step (installing R) and progresses by assuming no prior knowledge of programming in R or in any other language. In the later chapters, e.g., Chapters \@ref(ch3) and \@ref(ch4), an understanding of statistics at the introductory undergraduate level would be helpful but not strictly essential.

## Data Sets {-#data-sets}

Many of the data sets used in this book were simulated by the author. Cases in which the data set used was not simulated are noted and a citation to the data source is provided. 

The data sets used in this book are hosted on a GitHub repository maintained by the author. It is located here: **INSERT GITHUB LINK HERE**.

You have two main options for how to acquire the data used by this book:

1.  **Clone the whole repository**. You can download a zip folder containing all of the data for the book directly from GitHub:

    1.  click the green _Clone or download_ button at the top right,
    2.  click _Download ZIP_
    3.  unzip this folders contents into somewhere you know where to find it.
    
2.  **Download individual files at a time**. To download a single file from GitHub:

    1.  click on the file, 
    2.  click _Raw_ in the toolbar on the top right,
    3.  right-click anywhere in the document, and
    4.  click _Save As..._.

## Exercises {-}

Following each chapter, there is a set of exercises. Attempting and completing them, as they give you an opportunity to practice what you learned while reading and typing along. Solutions are provided at the end of this book, however you are **strongly** recommended to attempt to figure the problems out before looking to how the author would solve them.

Some exercises have bonus questions. These are intended to challenge you with some of the more difficult tasks shown in the chapter or ask you to extend what you learned to a completely different problem. If you can get all of the non-bonus questions without looking at the solutions too much, you can consider yourself to have good understanding of that chapter's material. If you can complete the bonus questions with little or no help, that means you have mastered that chapter's material!

## Keyboard Shortcuts

Several parts of this book in this book make reference to keyboard shortcuts. They are never necessary, but can help you be more efficient if you commit them to muscle memory. This book assumes you are using a PC for the keyboard shortcuts. If you are using a Mac, they will be different (in many cases, you may just need to swap out the **CTRL** keystroke for the **CMD** keystroke). For a complete list of RStudio's keyboard shortcuts, go to _Help > Keyboard Shortcuts Help_

## Development of this Book {-}

This book represents the third reincarnation of the Auburn R Workshop Series. The first version was written in Fall 2014 using Microsoft Word, but the author found that making even small changes was clunky. Individual session materials were created in separate documents, as were the exercises and solutions. 

The second version was written through R and RStudio using the R packages `rmarkdown` **CITE** and `knitr` **CITE**, which allowed the integration of text, code, and output all into one output file. This was completed in Fall 2015. Like the first version, individual session materials were created in separate documents. 

This third version was written through R and RStudio but used the R package `bookdown` **CITE** which allowed for the individual sessions to be combined into one "book" by turning each session into a chapter. This facilitated cross-references to topics covered in previous chapters and allows the reader to only refer to one location when trying to remember how to use a skill. It also allowed for multiple formats to be published including both HTML and PDF versions.

The book is hosted on [GitHub Pages](https://pages.github.com/). 

## About the Author {-}

Ben Staton is a PhD candidate in the School of Fisheries at Auburn University. He studies quantitative methods for assessing fish populations for use in harvest management, with a focus on Pacific salmon in western Alaska. Ben has been using R on a daily basis since the beginning of his graduate work in 2014. 
