<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to R for Natural Resource Scientists</title>
  <meta name="description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to R for Natural Resource Scientists" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="https://bstaton1.github.io/au-r-workshop/" class="uri">https://bstaton1.github.io/au-r-workshop/</a>" />
  <meta property="og:image" content="<a href="https://bstaton1.github.io/au-r-workshop/" class="uri">https://bstaton1.github.io/au-r-workshop/</a>cover_image.png" />
  <meta property="og:description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University." />
  <meta name="github-repo" content="bstaton1/au-r-workshop" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to R for Natural Resource Scientists" />
  
  <meta name="twitter:description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University." />
  <meta name="twitter:image" content="<a href="https://bstaton1.github.io/au-r-workshop/" class="uri">https://bstaton1.github.io/au-r-workshop/</a>cover_image.png" />

<meta name="author" content="Ben Staton">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ch2.html">
<link rel="next" href="ch4.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to R for Nat. Res. Sci.</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-is-covered"><i class="fa fa-check"></i>What is Covered?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#comp-prep"><i class="fa fa-check"></i>Prepare Your Computer</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-sets"><i class="fa fa-check"></i>Data Sets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notation"><i class="fa fa-check"></i>Text Conventions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#keyboard-shortcuts"><i class="fa fa-check"></i>Keyboard Shortcuts</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#development-of-this-book"><i class="fa fa-check"></i>Development of this Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Introduction to the R Environment</a><ul>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#chapter-overview"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#before-you-begin-install-r-and-rstudio"><i class="fa fa-check"></i>Before You Begin: Install R and RStudio</a></li>
<li class="chapter" data-level="1.1" data-path="ch1.html"><a href="ch1.html#the-r-studio-interface"><i class="fa fa-check"></i><b>1.1</b> The R Studio Interface</a><ul>
<li class="chapter" data-level="1.1.1" data-path="ch1.html"><a href="ch1.html#write-some-simple-code"><i class="fa fa-check"></i><b>1.1.1</b> Write Some Simple Code</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch1.html"><a href="ch1.html#scripts"><i class="fa fa-check"></i><b>1.2</b> Saving Your Code: Scripts</a></li>
<li class="chapter" data-level="1.3" data-path="ch1.html"><a href="ch1.html#working-dir"><i class="fa fa-check"></i><b>1.3</b> The Working Directory</a></li>
<li class="chapter" data-level="1.4" data-path="ch1.html"><a href="ch1.html#r-object-types"><i class="fa fa-check"></i><b>1.4</b> R Object Types</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ch1.html"><a href="ch1.html#functions"><i class="fa fa-check"></i><b>1.4.1</b> Functions</a></li>
<li class="chapter" data-level="1.4.2" data-path="ch1.html"><a href="ch1.html#vectors"><i class="fa fa-check"></i><b>1.4.2</b> Vectors</a></li>
<li class="chapter" data-level="1.4.3" data-path="ch1.html"><a href="ch1.html#matrices"><i class="fa fa-check"></i><b>1.4.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4.4" data-path="ch1.html"><a href="ch1.html#data-frames"><i class="fa fa-check"></i><b>1.4.4</b> Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ch1.html"><a href="ch1.html#factors"><i class="fa fa-check"></i><b>1.5</b> Factors</a></li>
<li class="chapter" data-level="1.6" data-path="ch1.html"><a href="ch1.html#vector-math"><i class="fa fa-check"></i><b>1.6</b> Vector Math</a></li>
<li class="chapter" data-level="1.7" data-path="ch1.html"><a href="ch1.html#sub"><i class="fa fa-check"></i><b>1.7</b> Data Subsets/Queries</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#exercise-1a"><i class="fa fa-check"></i>Exercise 1A</a></li>
<li class="chapter" data-level="1.8" data-path="ch1.html"><a href="ch1.html#read"><i class="fa fa-check"></i><b>1.8</b> Read External Data Files</a></li>
<li class="chapter" data-level="1.9" data-path="ch1.html"><a href="ch1.html#data-summaries"><i class="fa fa-check"></i><b>1.9</b> Explore the Data Set</a></li>
<li class="chapter" data-level="1.10" data-path="ch1.html"><a href="ch1.html#logicalboolean-operators"><i class="fa fa-check"></i><b>1.10</b> Logical/Boolean Operators</a></li>
<li class="chapter" data-level="1.11" data-path="ch1.html"><a href="ch1.html#logsub"><i class="fa fa-check"></i><b>1.11</b> Logical Subsetting</a></li>
<li class="chapter" data-level="1.12" data-path="ch1.html"><a href="ch1.html#if-else-and-ifelse"><i class="fa fa-check"></i><b>1.12</b> <code>if()</code>, <code>else</code>, and <code>ifelse()</code></a></li>
<li class="chapter" data-level="1.13" data-path="ch1.html"><a href="ch1.html#writing-output-files"><i class="fa fa-check"></i><b>1.13</b> Writing Output Files</a><ul>
<li class="chapter" data-level="1.13.1" data-path="ch1.html"><a href="ch1.html#csv-files"><i class="fa fa-check"></i><b>1.13.1</b> <code>.csv</code> Files</a></li>
<li class="chapter" data-level="1.13.2" data-path="ch1.html"><a href="ch1.html#saving-r-objects"><i class="fa fa-check"></i><b>1.13.2</b> Saving R Objects</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="ch1.html"><a href="ch1.html#user-funcs"><i class="fa fa-check"></i><b>1.14</b> User-Defined Functions</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#ex1b"><i class="fa fa-check"></i>Exercise 1B</a><ul>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#exercise-1b-bonus"><i class="fa fa-check"></i>Exercise 1B Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>2</b> Base R Plotting Basics</a><ul>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#chapter-overview-1"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#before-you-begin"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="2.1" data-path="ch2.html"><a href="ch2.html#r-plotting-lingo"><i class="fa fa-check"></i><b>2.1</b> R Plotting Lingo</a></li>
<li class="chapter" data-level="2.2" data-path="ch2.html"><a href="ch2.html#lower-level-plotting-functions"><i class="fa fa-check"></i><b>2.2</b> Lower Level Plotting Functions</a></li>
<li class="chapter" data-level="2.3" data-path="ch2.html"><a href="ch2.html#other-high-level-plotting-functions"><i class="fa fa-check"></i><b>2.3</b> Other High-Level Plotting Functions</a><ul>
<li class="chapter" data-level="2.3.1" data-path="ch2.html"><a href="ch2.html#the-bar-graph"><i class="fa fa-check"></i><b>2.3.1</b> The Bar Graph</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ch2.html"><a href="ch2.html#box-whisker"><i class="fa fa-check"></i><b>2.4</b> Box-and-Whisker Plots</a></li>
<li class="chapter" data-level="2.5" data-path="ch2.html"><a href="ch2.html#histograms"><i class="fa fa-check"></i><b>2.5</b> Histograms</a></li>
<li class="chapter" data-level="2.6" data-path="ch2.html"><a href="ch2.html#the-par-function"><i class="fa fa-check"></i><b>2.6</b> The <code>par</code> Function</a></li>
<li class="chapter" data-level="2.7" data-path="ch2.html"><a href="ch2.html#new-temporary-devices"><i class="fa fa-check"></i><b>2.7</b> New Temporary Devices</a></li>
<li class="chapter" data-level="2.8" data-path="ch2.html"><a href="ch2.html#multi-panel-plots"><i class="fa fa-check"></i><b>2.8</b> Multi-panel Plots</a></li>
<li class="chapter" data-level="2.9" data-path="ch2.html"><a href="ch2.html#legends"><i class="fa fa-check"></i><b>2.9</b> Legends</a></li>
<li class="chapter" data-level="2.10" data-path="ch2.html"><a href="ch2.html#exporting-plots"><i class="fa fa-check"></i><b>2.10</b> Exporting Plots</a><ul>
<li class="chapter" data-level="2.10.1" data-path="ch2.html"><a href="ch2.html#click-save"><i class="fa fa-check"></i><b>2.10.1</b> Click Save</a></li>
<li class="chapter" data-level="2.10.2" data-path="ch2.html"><a href="ch2.html#use-a-function-to-place-plot-in-a-new-file"><i class="fa fa-check"></i><b>2.10.2</b> Use a function to place plot in a new file</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="ch2.html"><a href="ch2.html#error-bars"><i class="fa fa-check"></i><b>2.11</b> Bonus Topic: Error Bars</a></li>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#ex2"><i class="fa fa-check"></i>Exercise 2</a><ul>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#exercise-2-bonus"><i class="fa fa-check"></i>EXERCISE 2 BONUS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>3</b> Basic Statistics</a><ul>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#chapter-overview-2"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#before-you-begin-1"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="3.1" data-path="ch3.html"><a href="ch3.html#lm"><i class="fa fa-check"></i><b>3.1</b> The General Linear Model</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ch3.html"><a href="ch3.html#regression"><i class="fa fa-check"></i><b>3.1.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="3.1.2" data-path="ch3.html"><a href="ch3.html#anova"><i class="fa fa-check"></i><b>3.1.2</b> ANOVA: Categorical predictors</a></li>
<li class="chapter" data-level="3.1.3" data-path="ch3.html"><a href="ch3.html#ancova-continuous-and-categorical-predictors"><i class="fa fa-check"></i><b>3.1.3</b> ANCOVA: Continuous and categorical predictors</a></li>
<li class="chapter" data-level="3.1.4" data-path="ch3.html"><a href="ch3.html#interactions"><i class="fa fa-check"></i><b>3.1.4</b> Interactions</a></li>
<li class="chapter" data-level="3.1.5" data-path="ch3.html"><a href="ch3.html#aic-model-selection"><i class="fa fa-check"></i><b>3.1.5</b> AIC Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ch3.html"><a href="ch3.html#glms"><i class="fa fa-check"></i><b>3.2</b> The Generalized Linear Model</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ch3.html"><a href="ch3.html#logis-regression"><i class="fa fa-check"></i><b>3.2.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="3.2.2" data-path="ch3.html"><a href="ch3.html#aic-model-selection-1"><i class="fa fa-check"></i><b>3.2.2</b> AIC Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ch3.html"><a href="ch3.html#dists"><i class="fa fa-check"></i><b>3.3</b> Probability Distributions</a></li>
<li class="chapter" data-level="3.4" data-path="ch3.html"><a href="ch3.html#nls"><i class="fa fa-check"></i><b>3.4</b> Bonus Topic: Non-linear Regression</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4.html"><a href="ch4.html"><i class="fa fa-check"></i><b>4</b> Monte Carlo Methods</a><ul>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#chapter-overview-3"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#before-you-begin-2"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#layout-of-this-chapter"><i class="fa fa-check"></i>Layout of This Chapter</a></li>
<li class="chapter" data-level="4.1" data-path="ch4.html"><a href="ch4.html#randomness"><i class="fa fa-check"></i><b>4.1</b> Introducing Randomness</a><ul>
<li class="chapter" data-level="4.1.1" data-path="ch4.html"><a href="ch4.html#random-deviates"><i class="fa fa-check"></i><b>4.1.1</b> Random deviates</a></li>
<li class="chapter" data-level="4.1.2" data-path="ch4.html"><a href="ch4.html#resampling"><i class="fa fa-check"></i><b>4.1.2</b> Resampling</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="ch4.html"><a href="ch4.html#reproducing-randomness"><i class="fa fa-check"></i><b>4.2</b> Reproducing Randomness</a></li>
<li class="chapter" data-level="4.3" data-path="ch4.html"><a href="ch4.html#replication"><i class="fa fa-check"></i><b>4.3</b> Replication</a><ul>
<li class="chapter" data-level="4.3.1" data-path="ch4.html"><a href="ch4.html#replicate"><i class="fa fa-check"></i><b>4.3.1</b> <code>replicate()</code></a></li>
<li class="chapter" data-level="4.3.2" data-path="ch4.html"><a href="ch4.html#for-loops"><i class="fa fa-check"></i><b>4.3.2</b> The <code>for()</code> loop</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ch4.html"><a href="ch4.html#adv-funcs"><i class="fa fa-check"></i><b>4.4</b> Function Writing</a></li>
<li class="chapter" data-level="4.5" data-path="ch4.html"><a href="ch4.html#mc-summaries"><i class="fa fa-check"></i><b>4.5</b> Summarization</a><ul>
<li class="chapter" data-level="4.5.1" data-path="ch4.html"><a href="ch4.html#central-tendency"><i class="fa fa-check"></i><b>4.5.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.5.2" data-path="ch4.html"><a href="ch4.html#variability"><i class="fa fa-check"></i><b>4.5.2</b> Variability</a></li>
<li class="chapter" data-level="4.5.3" data-path="ch4.html"><a href="ch4.html#frequencies"><i class="fa fa-check"></i><b>4.5.3</b> Frequencies</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ch4.html"><a href="ch4.html#sim-examples"><i class="fa fa-check"></i><b>4.6</b> Simulation-Based Examples</a><ul>
<li class="chapter" data-level="4.6.1" data-path="ch4.html"><a href="ch4.html#rnorm-ex"><i class="fa fa-check"></i><b>4.6.1</b> Test <code>rnorm</code></a></li>
<li class="chapter" data-level="4.6.2" data-path="ch4.html"><a href="ch4.html#power-ex"><i class="fa fa-check"></i><b>4.6.2</b> Stochastic Power Analysis</a></li>
<li class="chapter" data-level="4.6.3" data-path="ch4.html"><a href="ch4.html#harv-ex"><i class="fa fa-check"></i><b>4.6.3</b> Harvest Policy Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ch4.html"><a href="ch4.html#resample-examples"><i class="fa fa-check"></i><b>4.7</b> Resampling-Based Examples</a><ul>
<li class="chapter" data-level="4.7.1" data-path="ch4.html"><a href="ch4.html#boot-test-ex"><i class="fa fa-check"></i><b>4.7.1</b> The Bootstrap</a></li>
<li class="chapter" data-level="4.7.2" data-path="ch4.html"><a href="ch4.html#perm-test-ex"><i class="fa fa-check"></i><b>4.7.2</b> Permutation Test</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="ch4.html"><a href="ch4.html#exercise-4"><i class="fa fa-check"></i><b>4.8</b> Exercise 4</a><ul>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4a-required-material-only"><i class="fa fa-check"></i>Exercise 4A: Required Material Only</a></li>
<li><a href="ch4.html#exercise-4b-test-rnorm">Exercise 4B: Test <code>rnorm</code></a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4c-stochastic-power-analysis"><i class="fa fa-check"></i>Exercise 4C: Stochastic Power Analysis</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4d-harvest-policy-analysis"><i class="fa fa-check"></i>Exercise 4D: Harvest Policy Analysis</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4e-the-bootstrap"><i class="fa fa-check"></i>Exercise 4E: The Bootstrap</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4f-permutation-tests"><i class="fa fa-check"></i>Exercise 4F: Permutation Tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5.html"><a href="ch5.html"><i class="fa fa-check"></i><b>5</b> Large Data Manipulation</a><ul>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#chapter-overview-4"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#before-you-begin-3"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="5.1" data-path="ch5.html"><a href="ch5.html#aquiring-and-loading-packages"><i class="fa fa-check"></i><b>5.1</b> Aquiring and Loading Packages</a></li>
<li class="chapter" data-level="5.2" data-path="ch5.html"><a href="ch5.html#the-data"><i class="fa fa-check"></i><b>5.2</b> The Data</a></li>
<li class="chapter" data-level="5.3" data-path="ch5.html"><a href="ch5.html#change-format-using-melt"><i class="fa fa-check"></i><b>5.3</b> Change format using <code>melt()</code></a></li>
<li class="chapter" data-level="5.4" data-path="ch5.html"><a href="ch5.html#join-data-sets-with-merge"><i class="fa fa-check"></i><b>5.4</b> Join Data Sets with <code>merge()</code></a></li>
<li class="chapter" data-level="5.5" data-path="ch5.html"><a href="ch5.html#lagged-vectors"><i class="fa fa-check"></i><b>5.5</b> Lagged vectors</a></li>
<li class="chapter" data-level="5.6" data-path="ch5.html"><a href="ch5.html#adding-columns-with-mutate"><i class="fa fa-check"></i><b>5.6</b> Adding columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="5.7" data-path="ch5.html"><a href="ch5.html#apply-to-all-years"><i class="fa fa-check"></i><b>5.7</b> Apply to all years</a></li>
<li class="chapter" data-level="5.8" data-path="ch5.html"><a href="ch5.html#calculate-daily-means-with-summarize"><i class="fa fa-check"></i><b>5.8</b> Calculate Daily Means with <code>summarize()</code></a></li>
<li class="chapter" data-level="5.9" data-path="ch5.html"><a href="ch5.html#more-summarize"><i class="fa fa-check"></i><b>5.9</b> More <code>summarize()</code></a></li>
<li class="chapter" data-level="5.10" data-path="ch5.html"><a href="ch5.html#fit-the-model"><i class="fa fa-check"></i><b>5.10</b> Fit the Model</a></li>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#exercise-5"><i class="fa fa-check"></i>Exercise 5</a><ul>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#exercise-5-bonus"><i class="fa fa-check"></i>Exercise 5 Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6.html"><a href="ch6.html"><i class="fa fa-check"></i><b>6</b> Mapping and Spatial Analysis</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex1a-answers"><i class="fa fa-check"></i>Exercise 1A Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex1b-answers"><i class="fa fa-check"></i>Exercise 1B Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex2-answers"><i class="fa fa-check"></i>Exercise 2 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex3-answers"><i class="fa fa-check"></i>Exercise 3 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4a-answers"><i class="fa fa-check"></i>Exercise 4A Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4b-answers"><i class="fa fa-check"></i>Exercise 4B Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4c-answers"><i class="fa fa-check"></i>Exercise 4C Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4d-answers"><i class="fa fa-check"></i>Exercise 4D Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4e-answers"><i class="fa fa-check"></i>Exercise 4E Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4f-answers"><i class="fa fa-check"></i>Exercise 4F Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex5-answers"><i class="fa fa-check"></i>Exercise 5 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex6-answers"><i class="fa fa-check"></i>Exercise 6 Solutions</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R for Natural Resource Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch3" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Basic Statistics</h1>
<div id="chapter-overview-2" class="section level2 unnumbered">
<h2>Chapter Overview</h2>
<p>In this chapter, you will get familiar with the basics of using R for the purpose it was designed: statisitical analysis. You will learn how to:</p>
<ul>
<li>fit and interpret the output from various general linear models:
<ul>
<li>simple linear regression models</li>
<li>T-tests (also ANOVA)</li>
<li>ANCOVA models</li>
<li>Interactions</li>
</ul></li>
<li>conduct basic model selection</li>
<li>fit basic GLMs: the logistic regression model</li>
<li>Bonus topic: fitting non-linear regression models using <code>nls()</code></li>
</ul>
<p>R’s built-in statistical modeling framework is pretty intuitive and comprehensive. R has gained popularity as a statistics software and is commonly used both in academia and governmental resource agencies. This popularity is likely a result of its power, flexibility, intuitive nature, and price (free!). For many students, this chapter may be the one that is most immediately useful.</p>
<p><strong>IMPORTANT NOTE</strong>: If you did not attend the sessions corresponding to Chapters <a href="ch1.html#ch1">1</a> or <a href="ch2.html#ch2">2</a>, you are recommended to walk through the material found in those chapters before proceeding to this material. Also note that if you are confused about a topic, you can use <strong>CTRL + F</strong> to find previous cases where that topic has been discussed in this book.</p>
</div>
<div id="before-you-begin-1" class="section level2 unnumbered">
<h2>Before You Begin</h2>
<p>You should create a new directory and R script for your work in this Chapter. Create a new R script called <code>Ch3.R</code> and save it in the directory <code>C:/Users/YOU/Documents/R-Book/Chapter3</code>. Set your working directory to that location. Revisit the material in Sections <a href="ch1.html#scripts">1.2</a> and <a href="ch1.html#working-dir">1.3</a> for more details on these steps.</p>
</div>
<div id="lm" class="section level2">
<h2><span class="header-section-number">3.1</span> The General Linear Model</h2>
<p>Much of this chapter will focus on the general linear model, so it is important to become familiar with it. The general linear model is a family of models that allows you to determine the relationship (if any) between some continuous response variable (<span class="math inline">\(y\)</span>) and some predictor variable(s) (<span class="math inline">\(x_n\)</span>) and is often written as:</p>
<span class="math display" id="eq:lin-mod">\[\begin{equation}
  y_i=\beta_0 + \beta_1 x_{i1} + ... + \beta_j x_{ij}+ ... + \beta_n x_{in} + \varepsilon_i, \varepsilon_i \sim N(0,\sigma),
\tag{3.1}
\end{equation}\]</span>
<p>where the subscript <span class="math inline">\(i\)</span> represents an individual observation. The predictor variable(s) can be either categorical (i.e., grouping variables used in ANOVA, t-test, etc.), continuous (regression), or a combination of categorical and continuous (ANCOVA). The main focus is to estimate the coefficients (<span class="math inline">\(\beta\)</span>), and in some cases it is to determine if their values are “significantly” different from the value assumed by some null hypothesis.</p>
<p>The model makes several assumptions about the residuals<a href="#fn24" class="footnoteRef" id="fnref24"><sup>24</sup></a> to obtain estimates of the coefficients. For reliable inference, the residuals must:</p>
<ul>
<li>be independent</li>
<li>be normally-distributed</li>
<li>have constant variance across range of the x-axis</li>
</ul>
<p>In R, the general linear model is fitted using the <code>lm()</code> function. Here’s the basic syntax is <code>lm(y ~ x, data = dat)</code><a href="#fn25" class="footnoteRef" id="fnref25"><sup>25</sup></a>; it says: “fit a model with <code>y</code> as the response variable and <code>x</code> as the sole predictor variable, look for the variables <code>x</code> and <code>y</code> in a data frame called <code>dat</code>”.</p>
<div id="regression" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Simple Linear Regression</h3>
<p>Read the data found in <code>sockeye.csv</code> (see in the <a href="index.html#data-sets">instructions</a> for help with acquiring the data) into R. This is the same data set you used in <a href="ch2.html#ex2">Exercise 2</a> - revisit this section for more details on the meaning of the variables. These are real data and are presented in <span class="citation">Kline and Flagg (<a href="#ref-sockeye-cite">2014</a>)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;../Data/sockeye.csv&quot;</span>)
<span class="kw">head</span>(dat)</code></pre></div>
<pre><code>##   year  type weight fecund egg_size survival
## 1 1991 hatch     NA     NA       NA       NA
## 2 1992 hatch     NA     NA       NA       NA
## 3 1993 hatch   1801   2182    12.25    46.58
## 4 1994 hatch   1681   2134     7.92    50.98
## 5 1995 hatch   2630   1576    21.61    68.06
## 6 1996 hatch   2165   2171     8.74    63.43</code></pre>
<p>To fit a regression model using <code>lm()</code>, both <code>x</code> and <code>y</code> must be continous (numeric) variables. In the data set <code>dat</code>, two such variables are the <code>weight</code> and <code>fecund</code>. Fit a regression model where you link the average fecundity (number of eggs) of an individual year to the average weight (in grams) in that year. Ignore for now that the fish come from two sources: hatchery and wild origin.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1 =<span class="st"> </span><span class="kw">lm</span>(fecund <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> dat)</code></pre></div>
<p>If you run just the <code>fit1</code> object, you will see the model you ran along with the coefficient estimates of the intercept (<span class="math inline">\(\beta_0\)</span>) and the slope (<span class="math inline">\(\beta_1\)</span>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fecund ~ weight, data = dat)
## 
## Coefficients:
## (Intercept)       weight  
##   1874.6496       0.2104</code></pre>
<p>This model looks like this:</p>
<span class="math display" id="eq:lin-reg">\[\begin{equation}
  y_i=\beta_0 + \beta_1 x_{i1} + \varepsilon_i, \varepsilon_i \sim N(0,\sigma),
\tag{3.2}
\end{equation}\]</span>
<p>where <span class="math inline">\(x_{i1}\)</span> is <code>weight</code>. The coefficients are interpretted as:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: the y-intercept (mean <code>fecund</code> at zero <code>weight</code>)</li>
<li><span class="math inline">\(\beta_1\)</span>: the slope (change in <code>fecund</code> for one unit increase in <code>weight</code>)</li>
</ul>
<p>For more information about the model fit, you can use the <code>summary()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fecund ~ weight, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -873.67 -389.28  -71.65  482.96 1041.24 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1874.6496   269.4369   6.958 4.33e-08 ***
## weight         0.2104     0.1803   1.167    0.251    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 500.6 on 35 degrees of freedom
##   (7 observations deleted due to missingness)
## Multiple R-squared:  0.03745,    Adjusted R-squared:  0.009945 
## F-statistic: 1.362 on 1 and 35 DF,  p-value: 0.2511</code></pre>
<p>Again the coefficient estimates are shown, but now you see the uncertainty on the parameter estimates (standard errors), the test statistic, and the p-value testing the null hypothesis that each coefficient has a zero value. Here you can see that the p-value does not support rejection of the null hypothesis that the slope is zero. You can see the residual standard error (variability of data around the fitted line and the estimate of <span class="math inline">\(\sigma\)</span>), the <span class="math inline">\(R^2\)</span> value (the proportion of variation in <code>fecund</code> explained by variation in <code>weight</code>), and the p-value of the overall model.</p>
<p>You can easily see the model fit by using the <code>abline()</code> function. Make a new plot and add the fitted regression line:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(fecund <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> dat, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">cex =</span> <span class="fl">1.5</span>)
<span class="kw">abline</span>(fit1)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-111-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It fits, but not very well. It seems there are two groups: one with data points mostly above the line and one with data points mostly below the line. You’ll now run a new model to get at this.</p>
</div>
<div id="anova" class="section level3">
<h3><span class="header-section-number">3.1.2</span> ANOVA: Categorical predictors</h3>
<p>ANOVA models attempt to determine if the means of different groups are different. You can fit them in the same basic <code>lm()</code> framework. But first, notice that:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(dat<span class="op">$</span>type); <span class="kw">levels</span>(dat<span class="op">$</span>type)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre><code>## [1] &quot;hatch&quot; &quot;wild&quot;</code></pre>
<p>tells you the <code>type</code> variable is a factor. It has levels of <code>&quot;hatch&quot;</code> and <code>&quot;wild&quot;</code> which indicate the origin of the adult spawning fish sampled each year. If you pass <code>lm()</code> a predictor variable with a factor class, R will automatically fit it as an ANOVA model. See Section <a href="ch1.html#factors">1.5</a> for more details on factors. Factors have an explicit ordering of the levels. By default, this ordering happens alphabetically: if your factor has levels <code>&quot;a&quot;</code>, <code>&quot;b&quot;</code>, and <code>&quot;c&quot;</code>, they will be assigned the order of <code>1</code>, <code>2</code> and <code>3</code>, respectively. You can always see how R is ordering your factor by doing something similar to this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pairs =<span class="st"> </span><span class="kw">cbind</span>(
  <span class="kw">as.character</span>(dat<span class="op">$</span>type),
  <span class="kw">as.numeric</span>(dat<span class="op">$</span>type)
)

<span class="kw">head</span>(pairs); <span class="kw">tail</span>(pairs)</code></pre></div>
<pre><code>##      [,1]    [,2]
## [1,] &quot;hatch&quot; &quot;1&quot; 
## [2,] &quot;hatch&quot; &quot;1&quot; 
## [3,] &quot;hatch&quot; &quot;1&quot; 
## [4,] &quot;hatch&quot; &quot;1&quot; 
## [5,] &quot;hatch&quot; &quot;1&quot; 
## [6,] &quot;hatch&quot; &quot;1&quot;</code></pre>
<pre><code>##       [,1]   [,2]
## [39,] &quot;wild&quot; &quot;2&quot; 
## [40,] &quot;wild&quot; &quot;2&quot; 
## [41,] &quot;wild&quot; &quot;2&quot; 
## [42,] &quot;wild&quot; &quot;2&quot; 
## [43,] &quot;wild&quot; &quot;2&quot; 
## [44,] &quot;wild&quot; &quot;2&quot;</code></pre>
<p>The functions <code>as.character</code> and <code>as.numeric</code> are coersion functions: they attempt to change the way something is interpretted. Notice that the level <code>&quot;hatch&quot;</code> is assigned the order <code>1</code> because it comes before <code>&quot;wild&quot;</code> alphebetically. The first level is termed the <strong>reference level</strong> because it is the group that all other levels are compared to when fitting a model. You can change the reference level using <code>dat$type_rlvl = relevel(dat$type, ref = &quot;wild&quot;)</code>.</p>
<p>You are now ready to fit the ANOVA model, which will measure the size of the difference in the mean <code>fecund</code> between different levels of the factor <code>type</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit2 =<span class="st"> </span><span class="kw">lm</span>(fecund <span class="op">~</span><span class="st"> </span>type, <span class="dt">data =</span> dat)</code></pre></div>
<p>Think of this model as being written as:</p>
<span class="math display" id="eq:anova">\[\begin{equation}
  y_i=\beta_0 + \beta_1 x_{i1} + \varepsilon_i
\tag{3.3}
\end{equation}\]</span>
<p>and assume that <span class="math inline">\(x_{i1} = 0\)</span> if observation <span class="math inline">\(i\)</span> is a fish from the <code>&quot;hatch&quot;</code> level and <span class="math inline">\(x_{i1} = 1\)</span> if observation <span class="math inline">\(i\)</span> is a fish from the <code>&quot;wild&quot;</code> level. Note that Equations <a href="ch3.html#eq:lin-reg">(3.2)</a> and <a href="ch3.html#eq:anova">(3.3)</a> are the same, the only thing that differs is the coding of the variable <span class="math inline">\(x_{i1}\)</span>. In the ANOVA case:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> (the intercept) is the mean <code>fecund</code> for the <code>&quot;hatch&quot;</code> level and</li>
<li><span class="math inline">\(\beta_1\)</span> is the difference in mean <code>fecund</code>: <code>&quot;wild&quot;</code> - <code>&quot;hatch&quot;</code>.</li>
</ul>
<p>So when you run <code>coef(fit2)</code> to extract the coefficient estimates and get:</p>
<pre><code>## (Intercept)    typewild 
##   1846.2500    713.3971</code></pre>
<p>you see that the mean fecundity of hatchery fish is about 1846 eggs and that the average wild fish has about 713 more eggs than the average hatchery fish across all years. The fact that the p-value associated with the <code>typewild</code> coefficient when you run <code>summary(fit2)</code> is less than 0.05 indicates that there is statistical evidence that the difference in means is not zero.</p>
<p>Verify your interpretation of the coefficients:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m =<span class="st"> </span><span class="kw">tapply</span>(dat<span class="op">$</span>fecund, dat<span class="op">$</span>type, mean, <span class="dt">na.rm =</span> T)

<span class="co"># b0:</span>
m[<span class="dv">1</span>]</code></pre></div>
<pre><code>##   hatch 
## 1846.25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># b1:</span>
m[<span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>m[<span class="dv">1</span>]</code></pre></div>
<pre><code>##     wild 
## 713.3971</code></pre>
</div>
<div id="ancova-continuous-and-categorical-predictors" class="section level3">
<h3><span class="header-section-number">3.1.3</span> ANCOVA: Continuous and categorical predictors</h3>
<p>Now that you have seen that hatchery and wild fish tend to separate along the fecundity axis (as evidenced by the ANOVA results above), you would like to include this in your original regression model. You will fit two regression lines within the same model: one for hatchery fish and one for wild fish. This model is called an ANCOVA model and looks like this:</p>
<span class="math display" id="eq:ancova">\[\begin{equation}
  y_i=\beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \varepsilon_i
\tag{3.4}
\end{equation}\]</span>
<p>If <span class="math inline">\(x_{i1}\)</span> is <code>type</code> coded with 0’s and 1’s as in Section <a href="ch3.html#anova">3.1.2</a> and <span class="math inline">\(x_{i2}\)</span> is <code>weight</code>, then the coefficients are interpretted as:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: the y-intercept of the <code>&quot;hatch&quot;</code> level (the reference level)</li>
<li><span class="math inline">\(\beta_1\)</span>: the difference in mean <code>fecund</code> at the same weight: <code>&quot;wild&quot;</code> - <code>&quot;hatch&quot;</code></li>
<li><span class="math inline">\(\beta_2\)</span>: the slope of the <code>fecund</code> <em>vs.</em> <code>weight</code> relationship (this model assumes the lines have common slopes, i.e., that the lines are parallel)</li>
</ul>
<p>You can fit this model and extract the coefficents table from the summary:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit3 =<span class="st"> </span><span class="kw">lm</span>(fecund <span class="op">~</span><span class="st"> </span>type <span class="op">+</span><span class="st"> </span>weight, <span class="dt">data =</span> dat)
<span class="kw">summary</span>(fit3)<span class="op">$</span>coef</code></pre></div>
<pre><code>##                 Estimate  Std. Error  t value     Pr(&gt;|t|)
## (Intercept) 1039.6417645 175.0992184 5.937444 1.038268e-06
## typewild     866.9909998  96.2473387 9.007948 1.578239e-10
## weight         0.5173716   0.1051039 4.922477 2.164460e-05</code></pre>
<p>And you can plot the fit. Study this code to make sure you know what each is doing. Use what you know about the meanings of the three coefficients to decipher the two <code>abline()</code> commands. Remember that <code>abline()</code> takes takes two arguments: <code>a</code> is the intercept and <code>b</code> is the slope.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(fecund <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> dat, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>,
     <span class="dt">pch =</span> <span class="kw">ifelse</span>(dat<span class="op">$</span>type <span class="op">==</span><span class="st"> &quot;hatch&quot;</span>, <span class="dv">1</span>, <span class="dv">16</span>), <span class="dt">cex =</span> <span class="fl">1.5</span>)
<span class="kw">abline</span>(<span class="kw">coef</span>(fit3)[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)], <span class="dt">lty =</span> <span class="dv">2</span>)
<span class="kw">abline</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit3)[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]), <span class="kw">coef</span>(fit3)[<span class="dv">3</span>])
<span class="kw">legend</span>(<span class="st">&quot;bottom&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Hatchery&quot;</span>, <span class="st">&quot;Wild&quot;</span>), <span class="dt">pch =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">16</span>), <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),
       <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">pt.cex =</span> <span class="fl">1.5</span>, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="dt">horiz =</span> T)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-118-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="interactions" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Interactions</h3>
<p>Above, you have included an additional predictor variable (and parameter) in your model to help explain variation in the <code>fecund</code> variable. However, you have assumed that the effect of weight on fecundity is common between hatchery and wild fish (note the parallel lines in the figure above). You may have reason to believe that the effect of weight depends on the origin of the fish, e.g., wild fish may tend to accumulate more eggs than hatchery fish for the same increase in weight. Cases where the magnitude of the effect depends on the value of another predictor variable are known as “interactions”. You can write the interactive ANCOVA model like this:</p>
<span class="math display" id="eq:ancova-interact">\[\begin{equation}
  y_i=\beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i1} x_{i2} + \varepsilon_i
\tag{3.5}
\end{equation}\]</span>
<p>If <span class="math inline">\(x_{i1}\)</span> is <code>type</code> coded with 0’s and 1’s as in Section <a href="ch3.html#anova">3.1.2</a> and <span class="math inline">\(x_{i2}\)</span> is <code>weight</code>, then the coefficients are interpretted as:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: the y-intercept of the <code>&quot;hatch&quot;</code> level (the reference level)</li>
<li><span class="math inline">\(\beta_1\)</span>: the difference in y-intercept between the <code>&quot;wild&quot;</code> level and the <code>&quot;hatch&quot;</code> level.</li>
<li><span class="math inline">\(\beta_2\)</span>: the slope of the <code>&quot;hatch&quot;</code> level</li>
<li><span class="math inline">\(\beta_3\)</span>: the difference in slope between the <code>&quot;wild&quot;</code> level and the <code>&quot;hatch&quot;</code> level.</li>
</ul>
<p>You can fit this model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit4 =<span class="st"> </span><span class="kw">lm</span>(fecund <span class="op">~</span><span class="st"> </span>type <span class="op">+</span><span class="st"> </span>weight <span class="op">+</span><span class="st"> </span>type<span class="op">:</span>weight, <span class="dt">data =</span> dat)

<span class="co"># or</span>
<span class="co"># fit4 = lm(fecund ~ type * weight, data = dat)</span></code></pre></div>
<p>The first option above is more clear in its statement, but both do the same thing.</p>
<p>Plot the fit. Study these lines to make sure you know what each is doing. Use what you know about the meanings of the four coefficients to decipher the two <code>abline()</code> commands.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(fecund <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> dat, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>,
     <span class="dt">pch =</span> <span class="kw">ifelse</span>(dat<span class="op">$</span>type <span class="op">==</span><span class="st"> &quot;hatch&quot;</span>, <span class="dv">1</span>, <span class="dv">16</span>), <span class="dt">cex =</span> <span class="fl">1.5</span>)
<span class="kw">abline</span>(<span class="kw">coef</span>(fit4)[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)], <span class="dt">lty =</span> <span class="dv">2</span>)
<span class="kw">abline</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit4)[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]), <span class="kw">sum</span>(<span class="kw">coef</span>(fit4)[<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">4</span>)]))
<span class="kw">legend</span>(<span class="st">&quot;bottom&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Hatchery&quot;</span>, <span class="st">&quot;Wild&quot;</span>), <span class="dt">pch =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">16</span>), <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),
       <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">pt.cex =</span> <span class="fl">1.5</span>, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="dt">horiz =</span> T)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-120-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Based on the coefficients table:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit4)<span class="op">$</span>coef</code></pre></div>
<pre><code>##                     Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)     1175.7190847 174.545223  6.7358995 1.125255e-07
## typewild         -42.8721082 398.980751 -0.1074541 9.150794e-01
## weight             0.4300894   0.105592  4.0731253 2.732580e-04
## typewild:weight    0.7003389   0.299104  2.3414560 2.539681e-02</code></pre>
<p>It seems that fish of the different origins have approximately the same intercept, but that their slopes are quite different.</p>
</div>
<div id="aic-model-selection" class="section level3">
<h3><span class="header-section-number">3.1.5</span> AIC Model Selection</h3>
<p>You have now fitted four different models, each that makes different claims about how you can predict the fecundity of a given sockeye salmon at Redfish Lake. If you are interested in determining <em>which</em> of these models you should use for prediction, you need to use <strong>model selection</strong>. Model selection attempts to find the model that is likely to have the smallest out-of-sample prediction error (i.e., future predictions will be close to what actually happens). One model selection metric is the AIC<a href="#fn26" class="footnoteRef" id="fnref26"><sup>26</sup></a>. Lower AIC values mean the model should have better predictive performance. Obtain a simple AIC table from your fitted model objects and sort the table by increasing values of AIC:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab =<span class="st"> </span><span class="kw">AIC</span>(fit1, fit2, fit3, fit4)
tab[<span class="kw">order</span>(tab<span class="op">$</span>AIC),]</code></pre></div>
<pre><code>##      df      AIC
## fit4  5 522.0968
## fit3  4 525.7834
## fit2  3 543.6914
## fit1  3 568.9166</code></pre>
<p>In general, AIC values that are different by more than 2 units are interpretted as having importantly different predictive performance. Based on this very quick-and-dirty analysis, it seems that in predicting future fecundity, you would want to use the interactive ANCOVA model.</p>
</div>
</div>
<div id="glms" class="section level2">
<h2><span class="header-section-number">3.2</span> The Generalized Linear Model</h2>
<p>The models you fitted above were called “general linear models”. They all made the assumption that the residuals (<span class="math inline">\(\varepsilon_i\)</span>) are normally-distributed and that the response variable and the predictor variables are linearly related. Oftentimes data and analyses do not follow this assumption. For these cases you should often move to the broader family of statistical models known as <strong>generalized linear models</strong><a href="#fn27" class="footnoteRef" id="fnref27"><sup>27</sup></a>.</p>
<div id="logis-regression" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Logistic Regression</h3>
<p>One example is in the case of <strong>binary</strong> data. Binary data have two outcomes, e.g., success/failure, lived/died, male/female, spawned/gravid, happy/sad, etc. If you wish to predict how the probability of one outcome over the other changes depending on some other variable, then you need to use the <strong>logistic regression model</strong>, which is written as:</p>
<span class="math display" id="eq:logis-reg">\[\begin{equation}
  logit(p_i)=\beta_0 + \beta_1 x_{i1} + ... + \beta_j x_{ij}+ ... + \beta_n x_{in}, y_i \sim Bernoulli(p_i)
\tag{3.6}
\end{equation}\]</span>
<p>Where <span class="math inline">\(p_i\)</span> is the probability of success for trial <span class="math inline">\(i\)</span> (<span class="math inline">\(y_i = 1\)</span>) at the values of the predictor variables <span class="math inline">\(x_{ij}\)</span>. The <span class="math inline">\(logit(p_i)\)</span> is the <strong>link function</strong> that links the linear parameter scale to the data scale. It constrains the value of <span class="math inline">\(p_i\)</span> to be between 0 and 1 regardless of the values of the <span class="math inline">\(\beta\)</span> coefficients. The logit link function does this:</p>
<span class="math display" id="eq:logit">\[\begin{equation}
  logit(p_i) = log\left(\frac{p_i}{1-p_i}\right)
\tag{3.7}
\end{equation}\]</span>
<p>which is the natural logarithm of the <strong>odds</strong>, a measure of how likely the event is to happen relative to it not happening. Make an R function to calculate the logit transformation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logit =<span class="st"> </span><span class="cf">function</span>(p) {
  <span class="kw">log</span>(p<span class="op">/</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>p))
}</code></pre></div>
<p>If you have the result of <code>logit(p[i])</code> (which is given by the <span class="math inline">\(\beta\)</span> coefficients and the <span class="math inline">\(x_{ij}\)</span> data in Equation <a href="ch3.html#eq:logis-reg">(3.6)</a>) and need to get <code>p[i]</code>, you can apply the inverse logit function:</p>
<span class="math display" id="eq:expit">\[\begin{equation}
  expit(lp_i)=\frac{e^{lp_i}}{1 + e^{lp_i}}
\tag{3.8}
\end{equation}\]</span>
<p>where <span class="math inline">\(lp_i = logit(p_i)\)</span>. Make a function for the inverse logit transformation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">expit =<span class="st"> </span><span class="cf">function</span>(lp) {  <span class="co"># lp stands for logit(p)</span>
  <span class="kw">exp</span>(lp)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(lp))
}</code></pre></div>
<p>Because of the logit link function, the coefficients have different interpretations than in the general linear models you fitted in the previous section: they are expressed in terms of <strong>log odds</strong>.</p>
<p>Fit a logistic regression model to the sockeye salmon data. None of the variables of interest are binary, but you can create one. Look at the variable <code>dat$survival</code>. This is the average % survival of all eggs laid that make it to the “eye-egg” stage. Create a new variable <code>binary</code> which takes on a 0 if <code>dat$survival</code> is less than 70% and a 1 otherwise:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat<span class="op">$</span>binary =<span class="st"> </span><span class="kw">ifelse</span>(dat<span class="op">$</span>survival <span class="op">&lt;</span><span class="st"> </span><span class="dv">70</span>, <span class="dv">0</span>, <span class="dv">1</span>)</code></pre></div>
<p>This will be your response variable and your model will estimate how the probability of <code>binary</code> being a <code>1</code> changes (or doesn’t) depending on the value of other variables.</p>
<p>Analogous to the simple linear regression model (Section <a href="ch3.html#regression">3.1.1</a>), estimate how <span class="math inline">\(p\)</span> changes with <code>weight</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1 =<span class="st"> </span><span class="kw">glm</span>(binary <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> dat, <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(fit1)<span class="op">$</span>coef</code></pre></div>
<pre><code>##                 Estimate Std. Error   z value   Pr(&gt;|z|)
## (Intercept)  4.363441330 1.76943946  2.466002 0.01366306
## weight      -0.002819271 0.00125243 -2.251040 0.02438303</code></pre>
<p>The coefficients are interpretted as (remember, “success” is defined as having at least 70% egg survival to the stage of interest):</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: the log odds of success for a fish with zero weight (which is not all that important, let alone difficult to interpret). It can be transformed into more interpretable quantities:
<ul>
<li><span class="math inline">\(e^{\beta_0}\)</span> is the odds of success for fish with zero weight and</li>
<li><span class="math inline">\(expit(e^{\beta_0})\)</span> is the probability of success for fish with zero weight.</li>
</ul></li>
<li><span class="math inline">\(\beta_1\)</span>: the additive effect of fish weight on the log odds of success. More interpretable expressions are:
<ul>
<li><span class="math inline">\(e^{\beta_1}\)</span> is the ratio of the odds of success at two consective weights (e.g., 1500 and 1501) and Claims about <span class="math inline">\(e^{\beta_1}\)</span> are made as “for every one gram increase in weight, success became * <span class="math inline">\(e^{\beta_1}\)</span> times as likely to happen”.</li>
</ul></li>
<li>You can predict the probability of success at any weight using <span class="math inline">\(expit(\beta_0 + \beta_1 weight)\)</span></li>
</ul>
<p>You can plot the fitted model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a sequence of weights to predict at</span>
wt_seq =<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(dat<span class="op">$</span>weight, <span class="dt">na.rm =</span> T),
             <span class="kw">max</span>(dat<span class="op">$</span>weight, <span class="dt">na.rm =</span> t),
             <span class="dt">length =</span> <span class="dv">100</span>)

<span class="co"># extract the coefficients and get p</span>
p =<span class="st"> </span><span class="kw">expit</span>(<span class="kw">coef</span>(fit1)[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(fit1)[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>wt_seq)

<span class="co"># plot the relationship</span>
<span class="kw">plot</span>(p <span class="op">~</span><span class="st"> </span>wt_seq, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">las =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-127-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Fit another model comparing the probability of success between hatchery and wild fish (analogous to the ANOVA model in Section <a href="ch3.html#anova">3.1.2</a>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit2 =<span class="st"> </span><span class="kw">glm</span>(binary <span class="op">~</span><span class="st"> </span>type, <span class="dt">data =</span> dat, <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(fit2)<span class="op">$</span>coef</code></pre></div>
<pre><code>##               Estimate Std. Error    z value  Pr(&gt;|z|)
## (Intercept) -0.2006707  0.4494666 -0.4464641 0.6552620
## typewild     1.3793257  0.7272845  1.8965421 0.0578884</code></pre>
<p>An easier way to obtain the predicted probability is by using the <code>predict</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(fit2,
        <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;hatch&quot;</span>, <span class="st">&quot;wild&quot;</span>)),
        <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</code></pre></div>
<pre><code>##         1         2 
## 0.4500000 0.7647059</code></pre>
<p>This plugs in the two possible values of the predictor variable and asks for the fitted probabilities.</p>
<p>Incorporate the origin type into your original model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit3 =<span class="st"> </span><span class="kw">glm</span>(binary <span class="op">~</span><span class="st"> </span>type <span class="op">+</span><span class="st"> </span>weight, <span class="dt">data =</span> dat)</code></pre></div>
<p>and obtain/plot the fitted probabilities for each group:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_hatch =<span class="st"> </span><span class="kw">predict</span>(
  fit3, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">type =</span> <span class="st">&quot;hatch&quot;</span>, <span class="dt">weight =</span> wt_seq),
  <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>
)
p_wild =<span class="st"> </span><span class="kw">predict</span>(
  fit3, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">type =</span> <span class="st">&quot;wild&quot;</span>, <span class="dt">weight =</span> wt_seq),
  <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>
)

<span class="kw">plot</span>(p_wild <span class="op">~</span><span class="st"> </span>wt_seq, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">lty =</span> <span class="dv">1</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">las =</span><span class="dv">1</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Weight (g)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Pr(&gt;70% Egg Survival)&quot;</span>
     )
<span class="kw">lines</span>(p_hatch <span class="op">~</span><span class="st"> </span>wt_seq, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">lty =</span> <span class="dv">2</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Hatchery&quot;</span>, <span class="st">&quot;Wild&quot;</span>),
       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>), <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-131-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Look for an interaction (all the code is the same except use <code>glm(binary ~ type * weight)</code> instead of <code>glm(binary ~ type + weight)</code> and change everything to <code>fit4</code> instead of <code>fit3</code>).</p>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-132-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="aic-model-selection-1" class="section level3">
<h3><span class="header-section-number">3.2.2</span> AIC Model Selection</h3>
<p>You may have noticed that you just did the same analysis with <code>binary</code> as the response instead of <code>fecund</code>. Perform an AIC analysis to determine which model is likely to be best for prediction:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab =<span class="st"> </span><span class="kw">AIC</span>(fit1, fit2, fit3, fit4)
tab[<span class="kw">order</span>(tab<span class="op">$</span>AIC),]</code></pre></div>
<pre><code>##      df      AIC
## fit1  2 45.40720
## fit4  3 46.00622
## fit2  2 50.07577
## fit3  4 50.42090</code></pre>
<p>Oddly enough, the two best models are the simplest one and the most complex one, with <code>fit1</code> being the best, but not by a large margin.</p>
</div>
</div>
<div id="dists" class="section level2">
<h2><span class="header-section-number">3.3</span> Probability Distributions</h2>
<p>A probability distribution is a way of representing the probability of an event or value of a parameter and they are central to statistical theory. Some of the most commonly used distributions are summarized in Table <a href="ch3.html#tab:dist-table-html">3.1</a>, along with the suffixes of the functions in R that correspond to each distribution<a href="#fn28" class="footnoteRef" id="fnref28"><sup>28</sup></a>.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dist-table-html">Table 3.1: </span>A brief description of probability distributions commonly used in ecological problems, including the function suffix in R.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Type
</th>
<th style="text-align:left;">
Distribution
</th>
<th style="text-align:left;">
Common Uses
</th>
<th style="text-align:left;">
R Suffix
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;vertical-align: middle !important;" rowspan="4">
Continuous
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Models the relative frequency of outcomes that are symmetric around a mean, can be negative
</td>
<td style="text-align:left;">
<code>-norm()</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
Lognormal
</td>
<td style="text-align:left;">
Models the relative frequency of outcomes that are normally-distributed on the log-scale
</td>
<td style="text-align:left;">
<code>-lnorm()</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
Uniform
</td>
<td style="text-align:left;">
Models values that are between two endpoints and that all occur with the same frequency
</td>
<td style="text-align:left;">
<code>-unif()</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
Beta
</td>
<td style="text-align:left;">
Models values that are between 0 and 1
</td>
<td style="text-align:left;">
<code>-beta()</code>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;vertical-align: middle !important;" rowspan="3">
Discrete
</td>
<td style="text-align:left;">
Binomial
</td>
<td style="text-align:left;">
Models the number of successes from a given number of trials when there are only two possible outcomes and all trials have the same probability of success
</td>
<td style="text-align:left;">
<code>-binom()</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
Multinomial
</td>
<td style="text-align:left;">
The same as the binomial distribution, but when there are more than two possible outcomes
</td>
<td style="text-align:left;">
<code>-multinom()</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
Poisson
</td>
<td style="text-align:left;">
Used for count data in cases where the variance and mean are roughly equal
</td>
<td style="text-align:left;">
<code>-pois()</code>
</td>
</tr>
</tbody>
</table>
<p>In R, there are four different ways to use each of these distribution functions (each has a separate prefix):</p>
<ul>
<li><strong>The probability density (or mass) function</strong> (<code>d-</code>): the height of the probability distribution function at some given value of the random variable.</li>
<li><strong>The cumulative density function</strong> (<code>p-</code>): what is the sum of the probability densities for all random variables below the input argument <code>q</code>.</li>
<li><strong>The quantile function</strong> (<code>-q</code>): what value of the random variable do <code>p</code>% fall below?</li>
<li><strong>The random deviates function</strong> (<code>-r</code>): generates random variables from the distribution in proportion to their probability density.</li>
</ul>
<p>Suppose that <span class="math inline">\(x\)</span> represents the length of individual age 6 largemouth bass in your private fishing pond. Assume that <span class="math inline">\(x \sim N(\mu=500, \sigma=50)\)</span><a href="#fn29" class="footnoteRef" id="fnref29"><sup>29</sup></a>. Here is the usage of each of the distribution functions and a plot illustrating them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># parameters</span>
mu =<span class="st"> </span><span class="dv">500</span>; sig =<span class="st"> </span><span class="dv">50</span>

<span class="co"># a sequence of possible random variables (fish lengths)</span>
lengths =<span class="st"> </span><span class="kw">seq</span>(<span class="dv">200</span>, <span class="dv">700</span>, <span class="dt">length =</span> <span class="dv">100</span>)

<span class="co"># a sequence of possible cumulative probabilities</span>
cprobs =<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">length =</span> <span class="dv">100</span>)

densty =<span class="st"> </span><span class="kw">dnorm</span>(<span class="dt">x =</span> lengths, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sig)  <span class="co"># takes specific lengths</span>
cuprob =<span class="st"> </span><span class="kw">pnorm</span>(<span class="dt">q =</span> lengths, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sig)  <span class="co"># takes specific lengths</span>
quants =<span class="st"> </span><span class="kw">qnorm</span>(<span class="dt">p =</span> cprobs, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sig)   <span class="co"># takes specific probabilities</span>
random =<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="fl">1e4</span>, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sig)      <span class="co"># takes a number of random deviates to make</span>

<span class="co"># set up plotting region: see ?par for more details</span>
<span class="co"># notice the tricks to clean up the plot</span>
<span class="kw">par</span>(
  <span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),    <span class="co"># set up 2x2 regions</span>
  <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>),  <span class="co"># set narrower margins</span>
  <span class="dt">xaxs =</span> <span class="st">&quot;i&quot;</span>,        <span class="co"># remove &quot;x-buffer&quot;</span>
  <span class="dt">yaxs =</span> <span class="st">&quot;i&quot;</span>,        <span class="co"># remove &quot;y-buffer&quot;</span>
  <span class="dt">mgp =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="fl">0.4</span>,<span class="dv">0</span>),  <span class="co"># bring in axis titles ([1]) and tick labels ([2])</span>
  <span class="dt">tcl =</span> <span class="op">-</span><span class="fl">0.25</span>        <span class="co"># shorten tick marks</span>
)

<span class="kw">plot</span>(densty <span class="op">~</span><span class="st"> </span>lengths, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">main =</span> <span class="st">&quot;dnorm()&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Fish Length (mm)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, <span class="dt">las =</span> <span class="dv">1</span>,
     <span class="dt">yaxt =</span> <span class="st">&quot;n&quot;</span>) <span class="co"># turns off y-axis</span>
<span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">2</span>, <span class="dt">at =</span> <span class="kw">c</span>(<span class="fl">0.002</span>, <span class="fl">0.006</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="fl">0.002</span>, <span class="fl">0.006</span>), <span class="dt">las =</span> <span class="dv">2</span>)
<span class="kw">plot</span>(cuprob <span class="op">~</span><span class="st"> </span>lengths, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">main =</span> <span class="st">&quot;pnorm()&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Fish Length (mm)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Cumulative Probability&quot;</span>, <span class="dt">las =</span> <span class="dv">1</span>)
<span class="kw">plot</span>(quants <span class="op">~</span><span class="st"> </span>cprobs, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">main =</span> <span class="st">&quot;qnorm()&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;P&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;P Quantile Length (mm)&quot;</span>, <span class="dt">las =</span> <span class="dv">1</span>)
<span class="kw">hist</span>(random, <span class="dt">breaks =</span> <span class="dv">50</span>, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;rnorm()&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Fish Length (mm)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frequency&quot;</span>, <span class="dt">las =</span> <span class="dv">1</span>)
<span class="kw">box</span>() <span class="co"># add borders to the histogram</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:norm-plots"></span>
<img src="au-r-workshop_files/figure-html/norm-plots-1.png" alt="The four `-norm` functions with input (x-axis) and output (y-axis) displayed." width="624" />
<p class="caption">
Figure 3.1: The four <code>-norm</code> functions with input (x-axis) and output (y-axis) displayed.
</p>
</div>
<p>Notice that <code>pnorm()</code> and <code>qnorm()</code> are inverses of one another: if you put the output of one into the output of the other, you get the original input back:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(<span class="kw">pnorm</span>(<span class="dv">0</span>))</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p><code>pnorm(0)</code> asks R to find the probability that <span class="math inline">\(x\)</span> is less than zero for the standard normal distribution (<span class="math inline">\(N(0,1)\)</span> - this is the default if you don’t specify <code>mean</code> and <code>sig</code>). <code>qnorm(pnorm(0))</code> asks R to find the value of <span class="math inline">\(x\)</span> that <code>pnorm(0)</code> * 100% of the possible values fall below. If the nesting is confusing, this line is the same as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p =<span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">0</span>)
<span class="kw">qnorm</span>(p)</code></pre></div>
</div>
<div id="nls" class="section level2">
<h2><span class="header-section-number">3.4</span> Bonus Topic: Non-linear Regression</h2>
<p>You fitted linear and logistic regression models in Sections <a href="ch3.html#regression">3.1.1</a> and <a href="ch3.html#logis-regression">3.2.1</a>, however, R allows you to fit non-linear regression models as well.</p>
<p>First, read the data into R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;../Data/feeding.csv&quot;</span>); <span class="kw">summary</span>(dat)</code></pre></div>
<pre><code>##       prey            cons      
##  Min.   : 1.00   Min.   : 1.00  
##  1st Qu.:11.25   1st Qu.: 8.00  
##  Median :26.00   Median :11.00  
##  Mean   :25.08   Mean   : 9.92  
##  3rd Qu.:37.75   3rd Qu.:13.00  
##  Max.   :49.00   Max.   :15.00</code></pre>
<p>These are hypothetical data from an experiment in which you were interested in quantifying the functional feeding response<a href="#fn30" class="footnoteRef" id="fnref30"><sup>30</sup></a> of a fish predator on zooplankton in an aquarium. You experimentally manipulated the prey density (<code>prey</code>) and counted how many prey items were consumed (<code>cons</code>).</p>
<p>Plot the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(cons <span class="op">~</span><span class="st"> </span>prey, <span class="dt">data =</span> dat, <span class="dt">cex =</span> <span class="fl">1.5</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-138-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>You can see a distinct non-linearity to the relationship. The Holling Type II functional response<a href="#fn31" class="footnoteRef" id="fnref31"><sup>31</sup></a> has this functional form:</p>
<span class="math display" id="eq:func-resp">\[\begin{equation}
  y_i=\frac{ax_i}{1+ahx_i} + \varepsilon_i, \varepsilon_i \sim N(0, \sigma)
\tag{3.9}
\end{equation}\]</span>
<p>where <span class="math inline">\(x_i\)</span> is <code>prey</code> and <span class="math inline">\(y_i\)</span> is <code>cons</code>.</p>
<p>You can fit this model in R using the <code>nls()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit =<span class="st"> </span><span class="kw">nls</span>(cons <span class="op">~</span><span class="st"> </span>(a <span class="op">*</span><span class="st"> </span>prey)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>a <span class="op">*</span><span class="st"> </span>h <span class="op">*</span><span class="st"> </span>prey), <span class="dt">data =</span> dat,
          <span class="dt">start =</span> <span class="kw">c</span>(<span class="dt">a =</span> <span class="dv">3</span>, <span class="dt">h =</span> <span class="fl">0.1</span>))</code></pre></div>
<p>In general, it behaves very similarly to the <code>lm()</code> function, however there are a few differences:</p>
<ul>
<li>You need to specify the functional form of the curve you are attempting to fit. In using <code>lm()</code>, the terms are all additive (e.g., <code>type + weight</code>), but in using <code>nls()</code>, this is not the case. For example, note the use of division.</li>
<li>You may need to provide starting values for the parameters (coefficients) you are estimating. This is because <code>nls()</code> will use a search algorithm to find the parameters of the best fit line, and it may need to have a reasonable idea of where to start looking for it to work properly.</li>
<li>You cannot plot the fit using <code>abline()</code> anymore, because you have more parameters than just a slope and intercept, and the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is no longer linear.</li>
</ul>
<p>Despite these differences, you can obtain similar output as from <code>lm()</code> by using the <code>summary()</code>, <code>coef()</code>, and <code>predict()</code> functions. Draw the fitted line over top of the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prey_seq =<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(dat<span class="op">$</span>prey), <span class="kw">max</span>(dat<span class="op">$</span>prey), <span class="dt">length =</span> <span class="dv">100</span>)
cons_seq =<span class="st"> </span><span class="kw">predict</span>(fit, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">prey =</span> prey_seq))

<span class="kw">plot</span>(cons <span class="op">~</span><span class="st"> </span>prey, <span class="dt">data =</span> dat, <span class="dt">cex =</span> <span class="fl">1.5</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>)
<span class="kw">lines</span>(cons_seq <span class="op">~</span><span class="st"> </span>prey_seq, <span class="dt">lwd =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-140-1.png" width="672" style="display: block; margin: auto;" /></p>
<hr />
</div>
<div id="exercise-3" class="section level2 unnumbered">
<h2>Exercise 3</h2>
<p>You should create a new R script called <code>Ex3.R</code> in your working directory for this chapter. You will again be using the <code>sockeye.csv</code> data found in <span class="citation">Kline and Flagg (<a href="#ref-sockeye-cite">2014</a>)</span>.</p>
<p><em>The solutions to this exercise are found at the end of this book (<a href="exercise-solutions.html#ex3-answers">here</a>). You are <strong>strongly recommended</strong> to make a good attempt at completing this exercise on your own and only look at the solutions when you are truly stumped.</em></p>
<ol style="list-style-type: decimal">
<li>Perform the same analyses as conducted in Section <a href="ch3.html#lm">3.1</a> (simple linear regression, ANOVA, ANCOVA, ANCOVA with interaction), using <code>egg_size</code> as the response variable. The predictor variables you should use are <code>type</code> (categorical) and <code>year</code>. You should plot the fit for each model separately and perform an AIC analysis. Practice interpretting the coefficient estimates.</li>
<li>Perform the same analyses as conducted in Section <a href="ch3.html#glms">3.2</a>, this time using a success being having greater than 80% survival to the eyed-egg stage. Use <code>egg_size</code> and <code>type</code> as the predictor variables. You should plot the fitted lines for each model separately and perform an AIC analysis. Practice interpretting the coefficient estimates.</li>
<li><p>Make the same graphic as in Figure <a href="ch3.html#fig:norm-plots">3.1</a> with at least one of the other distributions listed in Table <a href="ch3.html#tab:dist-table-html">3.1</a> (other than the multinomial - being a multivariate distribution, it wouldn’t work well with this code). Try thinking of a variable from your work that meets the uses of each distribution in Table <a href="ch3.html#tab:dist-table-html">3.1</a> (or one that’s not listed). If you run into trouble, check out the help file for that distribution<a href="#fn32" class="footnoteRef" id="fnref32"><sup>32</sup></a>. ### Exercise 3 Bonus {-}</p></li>
<li><p>Fit a von Bertalannfy growth model to the data found in the <code>growth.csv</code> data file. Visit Section <a href="ch4.html#boot-test-ex">4.7.1</a> (particularly Equation <a href="ch4.html#eq:vonB">(4.2)</a>) for details on this model. Use the initial values: <code>linf = 600</code>, <code>k = 0.3</code>, <code>t0 = -0.2</code>. Plot the fitted line over top of the data.</p></li>
</ol>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-sockeye-cite">
<p>Kline, Paul A., and Thomas A. Flagg. 2014. “Putting the Red Back in Redfish Lake, 20 Years of Progress Toward Saving the Pacific Northwest’s Most Endangered Salmon Population.” <em>Fisheries</em> 39 (11): 488–500. doi:<a href="https://doi.org/10.1080/03632415.2014.966087">10.1080/03632415.2014.966087</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="24">
<li id="fn24"><p>The residuals (<span class="math inline">\(\varepsilon_i\)</span>) are the difference between the data point <span class="math inline">\(y_i\)</span> and the model prediction <span class="math inline">\(\hat{y}_i\)</span>: <span class="math inline">\(\varepsilon_i=y_i-\hat{y}_i\)</span><a href="ch3.html#fnref24">↩</a></p></li>
<li id="fn25"><p>This should look familar from Section <a href="ch2.html#box-whisker">2.4</a><a href="ch3.html#fnref25">↩</a></p></li>
<li id="fn26"><p>Akaike’s Information Criterion. An excellent overview of AIC with ecological applications is given in <span class="citation">Anderson, Burnham, and Thompson (<a href="#ref-aic-cite">2000</a>)</span><a href="ch3.html#fnref26">↩</a></p></li>
<li id="fn27"><p>General linear models are a member of this family<a href="ch3.html#fnref27">↩</a></p></li>
<li id="fn28"><p>For an excellent and ecologically-focused description of probability distributions, checkout Ben Bolker’s book, <em>Ecological Models and Data in R</em>. There is a free proof version online: <a href="https://ms.mcmaster.ca/~bolker/emdbook/book.pdf" class="uri">https://ms.mcmaster.ca/~bolker/emdbook/book.pdf</a><a href="ch3.html#fnref28">↩</a></p></li>
<li id="fn29"><p>English: <span class="math inline">\(x\)</span> is a normal random variable with mean equal to 500 and standard deviation equal to 50<a href="ch3.html#fnref29">↩</a></p></li>
<li id="fn30"><p>A functional response is the number of prey consumed by a predator at various prey densities<a href="ch3.html#fnref30">↩</a></p></li>
<li id="fn31"><p>This function rises quickly at low prey densities, but saturates at high densities<a href="ch3.html#fnref31">↩</a></p></li>
<li id="fn32"><p>Executing <code>?rnorm</code> or any other of the <code>-norm()</code> functions will take you to a page with info on all four function types for that distribution<a href="ch3.html#fnref32">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["au-r-workshop.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
