<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to R for Natural Resource Scientists</title>
  <meta name="description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to R for Natural Resource Scientists" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University." />
  <meta name="github-repo" content="bstaton1/au-r-workshop" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to R for Natural Resource Scientists" />
  
  <meta name="twitter:description" content="This is a first course in R programming for natural resource scientists. It was developed and has been primarily instructed at Auburn University." />
  

<meta name="author" content="Ben Staton">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ch4.html">
<link rel="next" href="ch6.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to R for Nat. Res. Sci.</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-is-covered"><i class="fa fa-check"></i>What is Covered?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#comp-prep"><i class="fa fa-check"></i>Prepare Your Computer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notation"><i class="fa fa-check"></i>Text Conventions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#keyboard-shortcuts"><i class="fa fa-check"></i>Keyboard Shortcuts</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#development-of-this-book"><i class="fa fa-check"></i>Development of this Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Introduction to the R Environment</a><ul>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#chapter-overview"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#before-you-begin"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="1.1" data-path="ch1.html"><a href="ch1.html#the-r-studio-interface"><i class="fa fa-check"></i><b>1.1</b> The R Studio Interface</a><ul>
<li class="chapter" data-level="1.1.1" data-path="ch1.html"><a href="ch1.html#write-some-simple-code"><i class="fa fa-check"></i><b>1.1.1</b> Write Some Simple Code</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch1.html"><a href="ch1.html#scripts"><i class="fa fa-check"></i><b>1.2</b> Saving Your Code: Scripts</a></li>
<li class="chapter" data-level="1.3" data-path="ch1.html"><a href="ch1.html#working-dir"><i class="fa fa-check"></i><b>1.3</b> The Working Directory</a></li>
<li class="chapter" data-level="1.4" data-path="ch1.html"><a href="ch1.html#r-object-types"><i class="fa fa-check"></i><b>1.4</b> R Object Types</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ch1.html"><a href="ch1.html#functions"><i class="fa fa-check"></i><b>1.4.1</b> Functions</a></li>
<li class="chapter" data-level="1.4.2" data-path="ch1.html"><a href="ch1.html#vectors"><i class="fa fa-check"></i><b>1.4.2</b> Vectors</a></li>
<li class="chapter" data-level="1.4.3" data-path="ch1.html"><a href="ch1.html#matrices"><i class="fa fa-check"></i><b>1.4.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4.4" data-path="ch1.html"><a href="ch1.html#data-frames"><i class="fa fa-check"></i><b>1.4.4</b> Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ch1.html"><a href="ch1.html#factors"><i class="fa fa-check"></i><b>1.5</b> Factors</a></li>
<li class="chapter" data-level="1.6" data-path="ch1.html"><a href="ch1.html#vector-math"><i class="fa fa-check"></i><b>1.6</b> Vector Math</a></li>
<li class="chapter" data-level="1.7" data-path="ch1.html"><a href="ch1.html#sub"><i class="fa fa-check"></i><b>1.7</b> Data Subsets/Queries</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#exercise-1a"><i class="fa fa-check"></i>Exercise 1A</a></li>
<li class="chapter" data-level="1.8" data-path="ch1.html"><a href="ch1.html#read"><i class="fa fa-check"></i><b>1.8</b> Read External Data Files</a></li>
<li class="chapter" data-level="1.9" data-path="ch1.html"><a href="ch1.html#data-summaries"><i class="fa fa-check"></i><b>1.9</b> Explore the Data Set</a></li>
<li class="chapter" data-level="1.10" data-path="ch1.html"><a href="ch1.html#logicalboolean-operators"><i class="fa fa-check"></i><b>1.10</b> Logical/Boolean Operators</a></li>
<li class="chapter" data-level="1.11" data-path="ch1.html"><a href="ch1.html#logsub"><i class="fa fa-check"></i><b>1.11</b> Logical Subsetting</a></li>
<li class="chapter" data-level="1.12" data-path="ch1.html"><a href="ch1.html#if-else-and-ifelse"><i class="fa fa-check"></i><b>1.12</b> <code>if()</code>, <code>else</code>, and <code>ifelse()</code></a></li>
<li class="chapter" data-level="1.13" data-path="ch1.html"><a href="ch1.html#writing-output-files"><i class="fa fa-check"></i><b>1.13</b> Writing Output Files</a><ul>
<li class="chapter" data-level="1.13.1" data-path="ch1.html"><a href="ch1.html#csv-files"><i class="fa fa-check"></i><b>1.13.1</b> <code>.csv</code> Files</a></li>
<li class="chapter" data-level="1.13.2" data-path="ch1.html"><a href="ch1.html#saving-r-objects"><i class="fa fa-check"></i><b>1.13.2</b> Saving R Objects</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="ch1.html"><a href="ch1.html#user-funcs"><i class="fa fa-check"></i><b>1.14</b> User-Defined Functions</a></li>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#ex1b"><i class="fa fa-check"></i>Exercise 1B</a><ul>
<li class="chapter" data-level="" data-path="ch1.html"><a href="ch1.html#exercise-1b-bonus"><i class="fa fa-check"></i>Exercise 1B Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2.html"><a href="ch2.html"><i class="fa fa-check"></i><b>2</b> Base R Plotting Basics</a><ul>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#chapter-overview-1"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#before-you-begin-1"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="2.1" data-path="ch2.html"><a href="ch2.html#r-plotting-lingo"><i class="fa fa-check"></i><b>2.1</b> R Plotting Lingo</a></li>
<li class="chapter" data-level="2.2" data-path="ch2.html"><a href="ch2.html#lower-level-plotting-functions"><i class="fa fa-check"></i><b>2.2</b> Lower Level Plotting Functions</a></li>
<li class="chapter" data-level="2.3" data-path="ch2.html"><a href="ch2.html#other-high-level-plotting-functions"><i class="fa fa-check"></i><b>2.3</b> Other High-Level Plotting Functions</a><ul>
<li class="chapter" data-level="2.3.1" data-path="ch2.html"><a href="ch2.html#the-bar-graph"><i class="fa fa-check"></i><b>2.3.1</b> The Bar Graph</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ch2.html"><a href="ch2.html#box-whisker"><i class="fa fa-check"></i><b>2.4</b> Box-and-Whisker Plots</a></li>
<li class="chapter" data-level="2.5" data-path="ch2.html"><a href="ch2.html#histograms"><i class="fa fa-check"></i><b>2.5</b> Histograms</a></li>
<li class="chapter" data-level="2.6" data-path="ch2.html"><a href="ch2.html#the-par-function"><i class="fa fa-check"></i><b>2.6</b> The <code>par()</code> Function</a></li>
<li class="chapter" data-level="2.7" data-path="ch2.html"><a href="ch2.html#new-temporary-devices"><i class="fa fa-check"></i><b>2.7</b> New Temporary Devices</a></li>
<li class="chapter" data-level="2.8" data-path="ch2.html"><a href="ch2.html#multi-panel-plots"><i class="fa fa-check"></i><b>2.8</b> Multi-panel Plots</a></li>
<li class="chapter" data-level="2.9" data-path="ch2.html"><a href="ch2.html#legends"><i class="fa fa-check"></i><b>2.9</b> Legends</a></li>
<li class="chapter" data-level="2.10" data-path="ch2.html"><a href="ch2.html#exporting-plots"><i class="fa fa-check"></i><b>2.10</b> Exporting Plots</a><ul>
<li class="chapter" data-level="2.10.1" data-path="ch2.html"><a href="ch2.html#click-save"><i class="fa fa-check"></i><b>2.10.1</b> Click Save</a></li>
<li class="chapter" data-level="2.10.2" data-path="ch2.html"><a href="ch2.html#file-devices"><i class="fa fa-check"></i><b>2.10.2</b> Use a function to place plot in a new file</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="ch2.html"><a href="ch2.html#error-bars"><i class="fa fa-check"></i><b>2.11</b> Bonus Topic: Error Bars</a></li>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#ex2"><i class="fa fa-check"></i>Exercise 2</a><ul>
<li class="chapter" data-level="" data-path="ch2.html"><a href="ch2.html#exercise-2-bonus"><i class="fa fa-check"></i>EXERCISE 2 BONUS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch3.html"><a href="ch3.html"><i class="fa fa-check"></i><b>3</b> Basic Statistics</a><ul>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#chapter-overview-2"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#before-you-begin-2"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="3.1" data-path="ch3.html"><a href="ch3.html#lm"><i class="fa fa-check"></i><b>3.1</b> The General Linear Model</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ch3.html"><a href="ch3.html#regression"><i class="fa fa-check"></i><b>3.1.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="3.1.2" data-path="ch3.html"><a href="ch3.html#anova"><i class="fa fa-check"></i><b>3.1.2</b> ANOVA: Categorical predictors</a></li>
<li class="chapter" data-level="3.1.3" data-path="ch3.html"><a href="ch3.html#ancova-continuous-and-categorical-predictors"><i class="fa fa-check"></i><b>3.1.3</b> ANCOVA: Continuous and categorical predictors</a></li>
<li class="chapter" data-level="3.1.4" data-path="ch3.html"><a href="ch3.html#interactions"><i class="fa fa-check"></i><b>3.1.4</b> Interactions</a></li>
<li class="chapter" data-level="3.1.5" data-path="ch3.html"><a href="ch3.html#aic-model-selection"><i class="fa fa-check"></i><b>3.1.5</b> AIC Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ch3.html"><a href="ch3.html#glms"><i class="fa fa-check"></i><b>3.2</b> The Generalized Linear Model</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ch3.html"><a href="ch3.html#logis-regression"><i class="fa fa-check"></i><b>3.2.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="3.2.2" data-path="ch3.html"><a href="ch3.html#aic-model-selection-1"><i class="fa fa-check"></i><b>3.2.2</b> AIC Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ch3.html"><a href="ch3.html#dists"><i class="fa fa-check"></i><b>3.3</b> Probability Distributions</a></li>
<li class="chapter" data-level="3.4" data-path="ch3.html"><a href="ch3.html#nls"><i class="fa fa-check"></i><b>3.4</b> Bonus Topic: Non-linear Regression</a></li>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a><ul>
<li class="chapter" data-level="" data-path="ch3.html"><a href="ch3.html#exercise-3-bonus"><i class="fa fa-check"></i>Exercise 3 Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch4.html"><a href="ch4.html"><i class="fa fa-check"></i><b>4</b> Monte Carlo Methods</a><ul>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#chapter-overview-3"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#before-you-begin-3"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#layout-of-this-chapter"><i class="fa fa-check"></i>Layout of This Chapter</a></li>
<li class="chapter" data-level="4.1" data-path="ch4.html"><a href="ch4.html#randomness"><i class="fa fa-check"></i><b>4.1</b> Introducing Randomness</a><ul>
<li class="chapter" data-level="4.1.1" data-path="ch4.html"><a href="ch4.html#random-deviates"><i class="fa fa-check"></i><b>4.1.1</b> Random deviates</a></li>
<li class="chapter" data-level="4.1.2" data-path="ch4.html"><a href="ch4.html#resampling"><i class="fa fa-check"></i><b>4.1.2</b> Resampling</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="ch4.html"><a href="ch4.html#reproducing-randomness"><i class="fa fa-check"></i><b>4.2</b> Reproducing Randomness</a></li>
<li class="chapter" data-level="4.3" data-path="ch4.html"><a href="ch4.html#replication"><i class="fa fa-check"></i><b>4.3</b> Replication</a><ul>
<li class="chapter" data-level="4.3.1" data-path="ch4.html"><a href="ch4.html#replicate"><i class="fa fa-check"></i><b>4.3.1</b> <code>replicate()</code></a></li>
<li class="chapter" data-level="4.3.2" data-path="ch4.html"><a href="ch4.html#for-loops"><i class="fa fa-check"></i><b>4.3.2</b> The <code>for()</code> loop</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ch4.html"><a href="ch4.html#adv-funcs"><i class="fa fa-check"></i><b>4.4</b> Function Writing</a></li>
<li class="chapter" data-level="4.5" data-path="ch4.html"><a href="ch4.html#mc-summaries"><i class="fa fa-check"></i><b>4.5</b> Summarization</a><ul>
<li class="chapter" data-level="4.5.1" data-path="ch4.html"><a href="ch4.html#central-tendency"><i class="fa fa-check"></i><b>4.5.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.5.2" data-path="ch4.html"><a href="ch4.html#variability"><i class="fa fa-check"></i><b>4.5.2</b> Variability</a></li>
<li class="chapter" data-level="4.5.3" data-path="ch4.html"><a href="ch4.html#frequencies"><i class="fa fa-check"></i><b>4.5.3</b> Frequencies</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ch4.html"><a href="ch4.html#sim-examples"><i class="fa fa-check"></i><b>4.6</b> Simulation-Based Examples</a><ul>
<li class="chapter" data-level="4.6.1" data-path="ch4.html"><a href="ch4.html#rnorm-ex"><i class="fa fa-check"></i><b>4.6.1</b> Test <code>rnorm</code></a></li>
<li class="chapter" data-level="4.6.2" data-path="ch4.html"><a href="ch4.html#power-ex"><i class="fa fa-check"></i><b>4.6.2</b> Stochastic Power Analysis</a></li>
<li class="chapter" data-level="4.6.3" data-path="ch4.html"><a href="ch4.html#harv-ex"><i class="fa fa-check"></i><b>4.6.3</b> Harvest Policy Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ch4.html"><a href="ch4.html#resample-examples"><i class="fa fa-check"></i><b>4.7</b> Resampling-Based Examples</a><ul>
<li class="chapter" data-level="4.7.1" data-path="ch4.html"><a href="ch4.html#boot-test-ex"><i class="fa fa-check"></i><b>4.7.1</b> The Bootstrap</a></li>
<li class="chapter" data-level="4.7.2" data-path="ch4.html"><a href="ch4.html#perm-test-ex"><i class="fa fa-check"></i><b>4.7.2</b> Permutation Test</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="ch4.html"><a href="ch4.html#exercise-4"><i class="fa fa-check"></i><b>4.8</b> Exercise 4</a><ul>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4a-required-material-only"><i class="fa fa-check"></i>Exercise 4A: Required Material Only</a></li>
<li><a href="ch4.html#exercise-4b-test-rnorm">Exercise 4B: Test <code>rnorm</code></a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4c-stochastic-power-analysis"><i class="fa fa-check"></i>Exercise 4C: Stochastic Power Analysis</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4d-harvest-policy-analysis"><i class="fa fa-check"></i>Exercise 4D: Harvest Policy Analysis</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4e-the-bootstrap"><i class="fa fa-check"></i>Exercise 4E: The Bootstrap</a></li>
<li class="chapter" data-level="" data-path="ch4.html"><a href="ch4.html#exercise-4f-permutation-tests"><i class="fa fa-check"></i>Exercise 4F: Permutation Tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch5.html"><a href="ch5.html"><i class="fa fa-check"></i><b>5</b> Large Data Manipulation</a><ul>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#chapter-overview-4"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#before-you-begin-4"><i class="fa fa-check"></i>Before You Begin</a></li>
<li class="chapter" data-level="5.1" data-path="ch5.html"><a href="ch5.html#aquiring-and-loading-packages"><i class="fa fa-check"></i><b>5.1</b> Aquiring and Loading Packages</a></li>
<li class="chapter" data-level="5.2" data-path="ch5.html"><a href="ch5.html#the-data"><i class="fa fa-check"></i><b>5.2</b> The Data</a></li>
<li class="chapter" data-level="5.3" data-path="ch5.html"><a href="ch5.html#change-format-using-melt"><i class="fa fa-check"></i><b>5.3</b> Change format using <code>melt()</code></a></li>
<li class="chapter" data-level="5.4" data-path="ch5.html"><a href="ch5.html#join-data-sets-with-merge"><i class="fa fa-check"></i><b>5.4</b> Join Data Sets with <code>merge()</code></a></li>
<li class="chapter" data-level="5.5" data-path="ch5.html"><a href="ch5.html#lagged-vectors"><i class="fa fa-check"></i><b>5.5</b> Lagged vectors</a></li>
<li class="chapter" data-level="5.6" data-path="ch5.html"><a href="ch5.html#adding-columns-with-mutate"><i class="fa fa-check"></i><b>5.6</b> Adding columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="5.7" data-path="ch5.html"><a href="ch5.html#apply-to-all-years"><i class="fa fa-check"></i><b>5.7</b> Apply to all years</a></li>
<li class="chapter" data-level="5.8" data-path="ch5.html"><a href="ch5.html#calculate-daily-means-with-summarize"><i class="fa fa-check"></i><b>5.8</b> Calculate Daily Means with <code>summarize()</code></a></li>
<li class="chapter" data-level="5.9" data-path="ch5.html"><a href="ch5.html#more-summarize"><i class="fa fa-check"></i><b>5.9</b> More <code>summarize()</code></a></li>
<li class="chapter" data-level="5.10" data-path="ch5.html"><a href="ch5.html#fit-the-model"><i class="fa fa-check"></i><b>5.10</b> Fit the Model</a></li>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#exercise-5"><i class="fa fa-check"></i>Exercise 5</a><ul>
<li class="chapter" data-level="" data-path="ch5.html"><a href="ch5.html#exercise-5-bonus"><i class="fa fa-check"></i>Exercise 5 Bonus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch6.html"><a href="ch6.html"><i class="fa fa-check"></i><b>6</b> Mapping and Spatial Analysis</a><ul>
<li class="chapter" data-level="6.1" data-path="ch6.html"><a href="ch6.html#ch6overview"><i class="fa fa-check"></i><b>6.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="6.2" data-path="ch6.html"><a href="ch6.html#ch6beforeyoubegin"><i class="fa fa-check"></i><b>6.2</b> Before You Begin</a></li>
<li class="chapter" data-level="6.3" data-path="ch6.html"><a href="ch6.html#intro"><i class="fa fa-check"></i><b>6.3</b> Geospatial Data</a></li>
<li class="chapter" data-level="6.4" data-path="ch6.html"><a href="ch6.html#Import"><i class="fa fa-check"></i><b>6.4</b> Importing Geospatial Data</a><ul>
<li class="chapter" data-level="6.4.1" data-path="ch6.html"><a href="ch6.html#csv-files-1"><i class="fa fa-check"></i><b>6.4.1</b> <code>.csv</code> files</a></li>
<li class="chapter" data-level="6.4.2" data-path="ch6.html"><a href="ch6.html#shp-files"><i class="fa fa-check"></i><b>6.4.2</b> <code>.shp</code> files</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="ch6.html"><a href="ch6.html#SpatPlot"><i class="fa fa-check"></i><b>6.5</b> Plotting</a><ul>
<li class="chapter" data-level="6.5.1" data-path="ch6.html"><a href="ch6.html#zoom"><i class="fa fa-check"></i><b>6.5.1</b> Zooming</a></li>
<li class="chapter" data-level="6.5.2" data-path="ch6.html"><a href="ch6.html#plot-selections"><i class="fa fa-check"></i><b>6.5.2</b> Plotting Selections</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="ch6.html"><a href="ch6.html#ManipSpat"><i class="fa fa-check"></i><b>6.6</b> Manipulating Spatial Data</a><ul>
<li class="chapter" data-level="6.6.1" data-path="ch6.html"><a href="ch6.html#crs"><i class="fa fa-check"></i><b>6.6.1</b> Changing the CRS</a></li>
<li class="chapter" data-level="6.6.2" data-path="ch6.html"><a href="ch6.html#clip"><i class="fa fa-check"></i><b>6.6.2</b> Clipping</a></li>
<li class="chapter" data-level="6.6.3" data-path="ch6.html"><a href="ch6.html#add-attr"><i class="fa fa-check"></i><b>6.6.3</b> Adding Attributes</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="ch6.html"><a href="ch6.html#Anal"><i class="fa fa-check"></i><b>6.7</b> Analysis</a><ul>
<li class="chapter" data-level="6.7.1" data-path="ch6.html"><a href="ch6.html#hr-Anal"><i class="fa fa-check"></i><b>6.7.1</b> Home Range Analysis</a></li>
<li class="chapter" data-level="6.7.2" data-path="ch6.html"><a href="ch6.html#finding-intersections-between-two-layers"><i class="fa fa-check"></i><b>6.7.2</b> Finding Intersections Between Two Layers</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="ch6.html"><a href="ch6.html#base-maps"><i class="fa fa-check"></i><b>6.8</b> Creating a Presentable Map</a></li>
<li class="chapter" data-level="6.9" data-path="ch6.html"><a href="ch6.html#other-r-mapping-packages"><i class="fa fa-check"></i><b>6.9</b> Other R Mapping Packages</a><ul>
<li class="chapter" data-level="6.9.1" data-path="ch6.html"><a href="ch6.html#ggmap"><i class="fa fa-check"></i><b>6.9.1</b> <code>{ggmap}</code></a></li>
<li class="chapter" data-level="6.9.2" data-path="ch6.html"><a href="ch6.html#leaflet"><i class="fa fa-check"></i><b>6.9.2</b> <code>{leaflet}</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch6.html"><a href="ch6.html#ex6"><i class="fa fa-check"></i>Exercise 6</a></li>
<li class="chapter" data-level="" data-path="ch6.html"><a href="ch6.html#exercise-6-bonus"><i class="fa fa-check"></i>Exercise 6 Bonus</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex2-answers"><i class="fa fa-check"></i>Exercise 1 Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex1a-answers"><i class="fa fa-check"></i>Exercise 1A Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex1b-answers"><i class="fa fa-check"></i>Exercise 1B Solutions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex2-answers"><i class="fa fa-check"></i>Exercise 2 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex3-answers"><i class="fa fa-check"></i>Exercise 3 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4-answers"><i class="fa fa-check"></i>Exercise 4 Solutions</a><ul>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4a-answers"><i class="fa fa-check"></i>Exercise 4A Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4b-answers"><i class="fa fa-check"></i>Exercise 4B Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4c-answers"><i class="fa fa-check"></i>Exercise 4C Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4d-answers"><i class="fa fa-check"></i>Exercise 4D Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4e-answers"><i class="fa fa-check"></i>Exercise 4E Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex4f-answers"><i class="fa fa-check"></i>Exercise 4F Solutions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex5-answers"><i class="fa fa-check"></i>Exercise 5 Solutions</a></li>
<li class="chapter" data-level="" data-path="exercise-solutions.html"><a href="exercise-solutions.html#ex6-answers"><i class="fa fa-check"></i>Exercise 6 Solutions</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/bstaton1/au-r-workshop-data" target="blank">Get the Data</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R for Natural Resource Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch5" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Large Data Manipulation</h1>
<div id="chapter-overview-4" class="section level2 unnumbered">
<h2>Chapter Overview</h2>
<p>Any data analyst will tell you that oftentimes the most difficult part of an analysis is simply getting the data in the proper format. Real data sets are messy: they have missing values, variables are often stored in multiple columns that would be better stored as rows, the same factor level may be coded as two or more different types<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>, or the required data are in several separate files. You get the point: sometimes significant data-wrangling may be required before you perform an analysis.</p>
<p>In this chapter, you will learn tricks to do more advanced data manipulation in R using two <strong>R packages</strong>:</p>
<ul>
<li><code>{reshape2}</code> <span class="citation">(Wickham <a href="#ref-R-reshape2">2007</a>)</span>: used for changing data between formats (wide and long)</li>
<li><code>{dplyr}</code> <span class="citation">(Wickham et al. <a href="#ref-R-dplyr">2017</a>)</span>: used for large data manipulations with a consistent and readable format.</li>
</ul>
<p>You will be turning daily observations of harvest and escapement (fish that are not harvested) into annual totals for the purpose of fitting a <strong>spawner-recruit analysis</strong> on a hypothetical pink salmon (<em>Oncorhynchus gorbuscha</em>) data set. More details and context on these terms and topics will be provided later.</p>
<p><strong>IMPORTANT NOTE</strong>: If you did not attend the sessions corresponding to Chapters <a href="ch1.html#ch1">1</a> or <a href="ch2.html#ch2">2</a>, you are recommended to walk through the material found in those chapters before proceeding to this material. Additionally, you will find the material in Section <a href="ch3.html#nls">3.4</a> helpful for the end of this chapter. Remember that if you are confused about a topic, you can use <strong>CTRL + F</strong> to find previous cases where that topic has been discussed in this book.</p>
</div>
<div id="before-you-begin-4" class="section level2 unnumbered">
<h2>Before You Begin</h2>
<p>You should create a new directory and R script for your work in this Chapter. Create a new R script called <code>Ch5.R</code> and save it in the directory <code>C:/Users/YOU/Documents/R-Book/Chapter5</code>. Set your working directory to that location. Revisit the material in Sections <a href="ch1.html#scripts">1.2</a> and <a href="ch1.html#working-dir">1.3</a> for more details on these steps.</p>
</div>
<div id="aquiring-and-loading-packages" class="section level2">
<h2><span class="header-section-number">5.1</span> Aquiring and Loading Packages</h2>
<p>An <strong>R package</strong> is a bunch of code, documentation, and data that someone has written and bundled into a consistent format for other R users to install and use in their R sessions. Packages make R incredibly flexible and extensible. If you are trying to do a specialized analysis that is not included in the base R distribution, it is likely that someone has already written a package that will allow you to do it!</p>
<p>In this chapter, you will be using some new packages that you likely don’t already have on your computer, so you will need to install them first:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)
<span class="kw">install.packages</span>(<span class="st">&quot;reshape2&quot;</span>)</code></pre></div>
<p>This requires an internet connection. You will see some text display in the console telling you the packages are being installed. Once the packages are installed, you need not re-install them in future sessions. However, if you install a new version of R, you will likely need to update your packages (i.e., re-install them).</p>
<p>Now that the packages are on your computer, you will need to load them into the current session:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)</code></pre></div>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 3.5.1</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(reshape2)</code></pre></div>
<p>These messages are telling you that there are functions in the <code>{dplyr}</code> package that have the same names as those already being used in the <code>{stats}</code> and <code>{base}</code> R packages. This is fine so long as you don’t want to use the original functions. If you wish to use the <code>{base}</code> version of the <code>filter()</code> function rather than the <code>{dplyr}</code> version, use it like this: <code>base::filter()</code>. Each time you close and reopen R, you will need to load any packages you want to use using <code>library()</code> again.</p>
</div>
<div id="the-data" class="section level2">
<h2><span class="header-section-number">5.2</span> The Data</h2>
<p>You have daily observations of catch and escapement for every other year between 1917 and 2015. Pink salmon have a simple life history where fish that spawned in an odd year return as adults to spawn in the next odd year. There is a commercial fishery in this system located at the river mouth which harvests fish as they enter the river. A counting tower is located upstream of the fishing grounds that counts the number of fish that escaped the fishery and will have a chance to spawn (this number is termed “escapement”). The ultimate goal is to obtain annual totals of spawners and total run (catch + escapement) for the purpose of fitting a spawner recruit analysis. You will perform some other analyses along the way directed at quantifying patterns in run timing.</p>
<p>Read in the two data sets for this chapter (see the <a href="index.html#data-sets">instructions</a> for details on acquiring data files):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">catch =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;../Data/daily_catch.csv&quot;</span>)
esc =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;../Data/daily_escape.csv&quot;</span>)</code></pre></div>
<p>Look at the first 6 rows and columns of the <code>catch</code> data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">catch[<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>##   doy y_1917 y_1919 y_1921 y_1923 y_1925
## 1 160    175    229    245    135   2685
## 2 161    221    501   1379   1504   2361
## 3 162    242    355   1149     13    277
## 4 163     90    197     52   2721    548
## 5 164    134    428    674    747   1209
## 6 165     76    224   1211   1231    772</code></pre>
<p>The column <code>doy</code> is the day of the year that each record corresponds to, and each column represents a different year. Notice the format of the <code>esc</code> data is the same:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">esc[<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>##   doy y_1917 y_1919 y_1921 y_1923 y_1925
## 1 161     90    189    161     73   1700
## 2 162    113    412    907    819   1495
## 3 163    124    292    756      7    176
## 4 164     46    162     34   1481    347
## 5 165     69    351    443    407    766
## 6 166     39    184    796    670    489</code></pre>
<p>But notice the first <code>doy</code> is one day later for <code>esc</code> than for <code>catch</code>. This is because of the time lag for fish to make it from the fishery grounds to the counting tower (a one day swim: fish that were in the fishing grounds on day <code>d</code> passed the counting tower on day <code>d+1</code> if they were not harvested).</p>
</div>
<div id="change-format-using-melt" class="section level2">
<h2><span class="header-section-number">5.3</span> Change format using <code>melt()</code></h2>
<p>These data are in what is called <strong>wide</strong> format: different levels of the <code>year</code> variable are stored as columns. A <strong>long</strong> format would have three columns: one for <code>doy</code>, <code>year</code>, and <code>catch</code> or <code>esc</code>. Turn the <code>catch</code> data frame into long format using the <code>melt()</code> function from <code>{reshape2}</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">long.catch =<span class="st"> </span><span class="kw">melt</span>(catch, <span class="dt">id.var =</span> <span class="st">&quot;doy&quot;</span>,
                  <span class="dt">variable.name =</span> <span class="st">&quot;year&quot;</span>,
                  <span class="dt">value.name =</span> <span class="st">&quot;catch&quot;</span>)
<span class="kw">head</span>(long.catch)</code></pre></div>
<pre><code>##   doy   year catch
## 1 160 y_1917   175
## 2 161 y_1917   221
## 3 162 y_1917   242
## 4 163 y_1917    90
## 5 164 y_1917   134
## 6 165 y_1917    76</code></pre>
<p>The first argument is the data frame to reformat, the second argument (<code>id.var</code>) is the variable that identifies one observation from another, here it is the <code>doy</code> that the count occurred on. In this case, it is actually all we need to run <code>melt</code> properly. The optional <code>variable.name</code> and <code>value.name</code> arguments specify the names of the other two columns. These default to “variable” and “value” if not specified. Do the same thing for escapement:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">long.esc =<span class="st"> </span><span class="kw">melt</span>(esc, <span class="dt">id.var =</span> <span class="st">&quot;doy&quot;</span>,
                <span class="dt">variable.name =</span> <span class="st">&quot;year&quot;</span>,
                <span class="dt">value.name =</span> <span class="st">&quot;esc&quot;</span>)
<span class="kw">head</span>(long.esc)</code></pre></div>
<pre><code>##   doy   year esc
## 1 161 y_1917  90
## 2 162 y_1917 113
## 3 163 y_1917 124
## 4 164 y_1917  46
## 5 165 y_1917  69
## 6 166 y_1917  39</code></pre>
<p>Anytime you do a large data manipulation like this, you should compare the new data set with the original to verify that it worked properly. Ask if <code>all</code> of the daily catches for a given year in the original data set match up to the new data set:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">all</span>(catch<span class="op">$</span>y_<span class="dv">2015</span> <span class="op">==</span><span class="st"> </span>long.catch[long.catch<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;y_2015&quot;</span>, <span class="st">&quot;catch&quot;</span>])</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>The single <code>TRUE</code> indicates that every element matches up for 2015 in the catch data, just like they should.</p>
<p>To reverse this action (i.e., to go from long format to wide format), you would use the <code>dcast()</code> function from <code>{reshape2}</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dcast</span>(long.catch, doy <span class="op">~</span><span class="st"> </span>year, <span class="dt">value.var =</span> <span class="st">&quot;catch&quot;</span>)</code></pre></div>
<p>The formula specifies which variables are ID variables on the left-hand side, and which variable should get expanded to multiple columns. The <code>value.var</code> argument indicates which variable will be placed into the columns.</p>
</div>
<div id="join-data-sets-with-merge" class="section level2">
<h2><span class="header-section-number">5.4</span> Join Data Sets with <code>merge()</code></h2>
<p>You now have two long format data sets. You can turn them into one data set with the <code>merge()</code> function (which is actually in the <code>{base}</code> package). <code>merge()</code> takes two data frames and joins them based on certain grouping variables. Here, you want to combine the data frames <code>long.catch</code> and <code>long.esc</code> into one data frame, and match the rows by the <code>doy</code> and <code>year</code> for each unique pair:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat =<span class="st"> </span><span class="kw">merge</span>(<span class="dt">x =</span> long.esc, <span class="dt">y =</span> long.catch,
            <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;doy&quot;</span>, <span class="st">&quot;year&quot;</span>), <span class="dt">all =</span> T)
<span class="kw">head</span>(dat)</code></pre></div>
<pre><code>##   doy   year esc catch
## 1 160 y_1917  NA   175
## 2 160 y_1919  NA   229
## 3 160 y_1921  NA   245
## 4 160 y_1923  NA   135
## 5 160 y_1925  NA  2685
## 6 160 y_1927  NA   163</code></pre>
<p>The <code>all = T</code> argument is important to specify here. It says that you wish to keep <strong>all</strong> of the unique records in the columns passed to <code>by</code> from both data frames. The <code>doy</code> in the catch data ranges from day 160 to day 209, whereas for escapement it ranges from day 161 to day 210. In this system, the fishery opens on the 160<sup>th</sup> day of every year, and the counting tower starts the 161<sup>st</sup> day. If you didn’t use <code>all = T</code>, you would drop all the rows in each data set that do not have a match in the other data set (you would lose day 160 and day 210 from every year). Notice that because no escapement observations were ever made on <code>doy</code> 160, the <code>esc</code> value on this day is <code>NA</code>.</p>
<p>Notice how the data set is now ordered by <code>doy</code> instead of <code>year</code>. This is not a problem, but if you want to reorder the data frame by <code>year</code>, you can use the <code>arrange()</code> function from <code>{dplyr}</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(dat, year))</code></pre></div>
<pre><code>##   doy   year esc catch
## 1 160 y_1917  NA   175
## 2 161 y_1917  90   221
## 3 162 y_1917 113   242
## 4 163 y_1917 124    90
## 5 164 y_1917  46   134
## 6 165 y_1917  69    76</code></pre>
</div>
<div id="lagged-vectors" class="section level2">
<h2><span class="header-section-number">5.5</span> Lagged vectors</h2>
<p>The present task is to the calculate daily cumulative run proportion<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a> in 2015 for comparison to the other years. Given the information you have, this task would be very cumbersome if not for the flexibility allowed by <code>{dplyr}</code>.</p>
<p>Remember the counting tower is an average one day swim for the salmon from the fishing grounds. This means that the escapement counts are <strong>lagged</strong> relative to the catch counts. If you want the daily run (defined as the number of fish in the fishing grounds each day), you need to account for this lag. An easy way to think about the lag is to show it graphically. First, pull out one year of data using the <code>filter()</code> function in <code>{dplyr}</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y15 =<span class="st"> </span><span class="kw">filter</span>(dat, year <span class="op">==</span><span class="st"> &quot;y_2015&quot;</span>)
<span class="kw">head</span>(y15)</code></pre></div>
<pre><code>##   doy   year  esc catch
## 1 160 y_2015   NA  3342
## 2 161 y_2015 2293  2352
## 3 162 y_2015 1614    88
## 4 163 y_2015   61  3270
## 5 164 y_2015 2244  5080
## 6 165 y_2015 3486   379</code></pre>
<p>The <code>{base}</code> analog to the <code>filter()</code> function is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y15 =<span class="st"> </span>dat[dat<span class="op">$</span>year <span class="op">==</span><span class="st"> &quot;y_2015&quot;</span>, ]
<span class="co"># or</span>
y15 =<span class="st"> </span><span class="kw">subset</span>(dat, year <span class="op">==</span><span class="st"> &quot;y_2015&quot;</span>)</code></pre></div>
<p>They take about the same amount of code to write, but <code>filter()</code> has some advantages when used with other <code>{dplyr}</code> functions that will be discussed later. Now plot the daily catch and escapement (not cumulative yet) for 2015:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(catch <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> y15, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;DOY&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Count&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Raw Data&quot;</span>)
<span class="kw">lines</span>(esc <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> y15, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Catch&quot;</span>, <span class="st">&quot;Escapement&quot;</span>), 
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">lty =</span> <span class="dv">1</span>, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Notice how the escapement counts are shifted to the right by one day. This is the lag. To account for it, you can use the <code>lag()</code> function from <code>{dplyr}</code>. <code>lag()</code> works by lagging some vector by <code>n</code> elements (it shifts every element in the vector <code>n</code> places to the right by putting <code>n</code> <code>NAs</code> at the front and removing the last <code>n</code> elements from the original vector). One way to fix the lag problem would be to use <code>lag()</code> on <code>catch</code> to make the days match up with <code>esc</code> (don’t lag <code>esc</code> because that would just lag it by <code>n</code> additional days):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">lag</span>(catch, <span class="dt">n =</span> <span class="dv">1</span>) <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> y15, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;DOY&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Count&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;With lag(catch)&quot;</span>)
<span class="kw">lines</span>(esc <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> y15, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Catch&quot;</span>, <span class="st">&quot;Escapement&quot;</span>),
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">lty =</span> <span class="dv">1</span>, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-20-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Notice how the two curves line up better now.</p>
</div>
<div id="adding-columns-with-mutate" class="section level2">
<h2><span class="header-section-number">5.6</span> Adding columns with <code>mutate()</code></h2>
<p>Apply this same idea to get the total daily run (what was harvested plus what was not). Make a function to take the two vectors (catch and escapement), lag one, and then sum them. Howevery, you don’t want to move catch forward a day; you need to move escapement back a day. The opposite of <code>lag()</code> is <code>lead()</code>. The way to think of this is that <code>lag()</code> lags a vector, and <code>lead()</code> unlags a vector. <code>lead()</code> shifts every element to the left by <code>n</code> elements by removing the first <code>n</code> elements of the original vector and adding <code>n</code> <code>NAs</code> to the end. This is what your function should look like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lag_sum =<span class="st"> </span><span class="cf">function</span>(x, y, <span class="dt">n =</span> <span class="dv">1</span>){
  <span class="co"># x is lagged from y by n days</span>
  <span class="kw">rowSums</span>(<span class="kw">cbind</span>(<span class="kw">lead</span>(x, n), y), <span class="dt">na.rm =</span> T)
}</code></pre></div>
<p>Note the use of <code>na.rm = T</code> to specify that summing a number with an <code>NA</code> should still return a number. If two <code>NAs</code> are summed, the result will be a zero.</p>
<p>Try out the <code>lag_sum()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lag_sum</span>(y15<span class="op">$</span>esc, y15<span class="op">$</span>catch)</code></pre></div>
<p>Add this column to your data set. You add columns in <code>{dplyr}</code> using <code>mutate()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y15 =<span class="st"> </span><span class="kw">mutate</span>(y15, <span class="dt">run =</span> <span class="kw">lag_sum</span>(esc, catch))</code></pre></div>
<p>The <code>{base}</code> equivalent to <code>mutate()</code> is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y15<span class="op">$</span>run =<span class="st"> </span><span class="kw">lag_sum</span>(y15<span class="op">$</span>esc, y15<span class="op">$</span>catch)</code></pre></div>
<p><code>mutate()</code> has advantages when used with other <code>{dplyr}</code> functions that will be shown soon. Use the new variable <code>run</code> to calculate two new variables: the cumulative run by day (<code>crun</code>) and cumulative run proportion by day (<code>cprun</code>). Cumulative means that each new element is the value that occurred on that day plus all of the values that happened on days before it. You can use R’s <code>cumsum()</code> for this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y15 =<span class="st"> </span><span class="kw">mutate</span>(y15, <span class="dt">crun =</span> <span class="kw">cumsum</span>(run), <span class="dt">cprun =</span> crun<span class="op">/</span><span class="kw">sum</span>(run, <span class="dt">na.rm =</span> T))</code></pre></div>
<p>Here is one advantage of <code>mutate()</code>: you can refer to a variable you just created to make a new variable within the same function. You would have to split this into two lines to do it in <code>{base}</code>. Indeed, you could have made <code>run</code>, <code>crun</code>, and <code>cprun</code> all in the same <code>mutate()</code> call. Plot <code>cprun</code><a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(cprun <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> y15, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),
     <span class="dt">xlab =</span> <span class="st">&quot;DOY&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Cumulative Run Proportion&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-27-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="apply-to-all-years" class="section level2">
<h2><span class="header-section-number">5.7</span> Apply to all years</h2>
<p>You have just obtained the daily and cumulative run for one year (2015), but <code>{dplyr}</code> makes it easy to apply these same manipulations to all years. To really see the advantage of <code>{dplyr}</code>, you’ll need to learn to use piping. A code <strong>pipe</strong> is one that takes the result of one function and inserts it into the input of another function. Here is a basic example of a pipe:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">10</span>) <span class="op">%&gt;%</span><span class="st"> </span>length</code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>The pipe took the result of <code>rnorm(10)</code> and passed it as the first argument to the <code>length</code> function. This allows you to string together commands so you aren’t continuously making intermediate objects or nesting a ton of functions together. The pipe essentially does this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">10</span>); <span class="kw">length</span>(x); <span class="kw">rm</span>(x)</code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>The reason piping works so well with <code>{dplyr}</code> is because its functions are designed to take a data frame as input as the first argument and return another data frame as output. This allows you to string them together with pipes. Do a more complex pipe: take your main data frame (<code>dat</code>), group it by <code>year</code>, and pass it to a <code>mutate()</code> call that will add the new three columns to the entire data set:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat =<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">run =</span> <span class="kw">lag_sum</span>(esc, catch), 
         <span class="dt">crun =</span> <span class="kw">cumsum</span>(run), 
         <span class="dt">cprun =</span> crun<span class="op">/</span><span class="kw">sum</span>(run, <span class="dt">na.rm =</span> T))

<span class="kw">arrange</span>(dat, year)</code></pre></div>
<pre><code>## # A tibble: 2,550 x 7
## # Groups:   year [50]
##      doy year     esc catch   run  crun  cprun
##    &lt;int&gt; &lt;fct&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1   160 y_1917    NA   175  265.  265. 0.0127
##  2   161 y_1917    90   221  334.  599. 0.0288
##  3   162 y_1917   113   242  366.  965. 0.0464
##  4   163 y_1917   124    90  136. 1101. 0.0530
##  5   164 y_1917    46   134  203. 1304. 0.0627
##  6   165 y_1917    69    76  115. 1419. 0.0683
##  7   166 y_1917    39    89  134. 1553. 0.0747
##  8   167 y_1917    45   139  210. 1763. 0.0848
##  9   168 y_1917    71   127  192. 1955. 0.0941
## 10   169 y_1917    65    61   92. 2047. 0.0985
## # ... with 2,540 more rows</code></pre>
<p>The <code>group_by()</code> function is spectacular: you grouped the data frame by <code>year</code>, which tells the rest of the functions in the pipe to apply its commands to each year independently. With this function, you can group your data in any way you please and calculate statistics on a group-by-group basis. Note that in this example, it doesn’t do much for you, because the data are so neat (all years have the same number of days, and <code>NAs</code> in all of the same places, etc.), but for data that are messier, this trick is very handy. Also note that the <code>dat</code> object looks a little different. When you print it, it only shows the first 10 rows. This is a <code>{dplyr}</code> feature that prevents you from printing a huge data set to the console.</p>
<p>Now plot the cumulative run proportion by day for each year, highlighting 2015:</p>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-31-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(sp)
<span class="co"># make an empty plot</span>
<span class="kw">plot</span>(<span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">y =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;n&quot;</span>, <span class="dt">xlim =</span> <span class="kw">range</span>(dat<span class="op">$</span>doy), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),
     <span class="dt">xlab =</span> <span class="st">&quot;DOY&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Cumulative Run Proportion&quot;</span>)

years =<span class="st"> </span><span class="kw">levels</span>(dat<span class="op">$</span>year)

<span class="co"># use sapply to &quot;loop&quot; through years, drawing lines for each</span>
tmp =<span class="st"> </span><span class="kw">sapply</span>(years, <span class="cf">function</span>(x) {
  <span class="kw">lines</span>(cprun <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> <span class="kw">filter</span>(dat, year <span class="op">==</span><span class="st"> </span>x),
        <span class="dt">col =</span> <span class="kw">ifelse</span>(x <span class="op">==</span><span class="st"> &quot;y_2015&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;grey&quot;</span>))
})</code></pre></div>
</div>
<div id="calculate-daily-means-with-summarize" class="section level2">
<h2><span class="header-section-number">5.8</span> Calculate Daily Means with <code>summarize()</code></h2>
<p>Oftentimes, you want to calculate a statistic for a value across grouping variables, like year or site or day. Remember the <code>tapply()</code> function does this in <code>{base}</code>. Here you want to calculate the mean cumulative run proportion for each day averaged across years. For this, you can make use of the <code>summarize()</code> function in <code>{dplyr}</code>. Begin by ungrouping the data to remove the <code>year</code> groups and grouping the data by <code>doy</code>. This will allow you to calculate the mean proportion by day. You then pass this grouped data frame to <code>summarize()</code> which will apply the <code>mean()</code> function to the cumulative run proportions across all years on a particular day. It will do this for all days:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean_cprun =<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>ungroup <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(doy) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">cprun =</span> <span class="kw">mean</span>(cprun))
<span class="kw">head</span>(mean_cprun)</code></pre></div>
<pre><code>## # A tibble: 6 x 2
##     doy   cprun
##   &lt;int&gt;   &lt;dbl&gt;
## 1   160 0.00970
## 2   161 0.0194 
## 3   162 0.0291 
## 4   163 0.0387 
## 5   164 0.0491 
## 6   165 0.0579</code></pre>
<p>The way to do this in <code>{base}</code> is with <code>tapply()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(dat<span class="op">$</span>cprun, dat<span class="op">$</span>doy, mean)[<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>##         160         161         162         163         164         165 
## 0.009699779 0.019400196 0.029111609 0.038735562 0.049130566 0.057901058</code></pre>
<p>Note that you get the same result, only the output from <code>tapply()</code> is a vector, and the output of <code>summarize()</code> is a data frame.</p>
<p>One disadvantage of the <code>summarize()</code> function, however, is that it can only be used to apply functions that give one number as output (e.g., <code>mean()</code>, <code>max()</code>, <code>sd()</code>, <code>length()</code>, etc.). These are called <strong>aggregate</strong> functions: they take a bunch of numbers and aggregate them into one number. <code>tapply()</code> does not have this constraint. Illustrate this by trying to use the <code>range()</code> function (which combines the minimum and maximum values of some vector into another vector of length 2).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with summarise</span>
dat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>ungroup <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(doy) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">range =</span> <span class="kw">range</span>(cprun))</code></pre></div>
<pre><code>## Error in summarise_impl(.data, dots): Column `range` must be length 1 (a summary value), not 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with tapply</span>
<span class="kw">tapply</span>(dat<span class="op">$</span>cprun, dat<span class="op">$</span>doy, range)[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</code></pre></div>
<pre><code>## $`160`
## [1] 0.0002721184 0.0256423751
## 
## $`161`
## [1] 0.001485884 0.048191292
## 
## $`162`
## [1] 0.003895501 0.057528072
## 
## $`163`
## [1] 0.01450474 0.07435435
## 
## $`164`
## [1] 0.01797648 0.08253284</code></pre>
<p>You can see that <code>tapply()</code> allows you to do this (but gives a list), whereas <code>summarize()</code> returns a short and informative error. You could very easily fix the problem by making minimum and maximum columns in the same <code>summarize()</code> call:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat <span class="op">%&gt;%</span>
<span class="st">  </span>ungroup <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(jday) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">min =</span> <span class="kw">min</span>(cprun), <span class="dt">max =</span> <span class="kw">max</span>(cprun))</code></pre></div>
<p>Add the mean cumulative run proportion to our plot (use <code>lines()</code> just like before, add it after the <code>sapply()</code> call):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lines</span>(cprun <span class="op">~</span><span class="st"> </span>doy, <span class="dt">data =</span> mean_cprun, <span class="dt">lwd =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-38-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It looks like 2015 started like an average year but the peak of the run happened a couple days earlier than average.</p>
</div>
<div id="more-summarize" class="section level2">
<h2><span class="header-section-number">5.9</span> More <code>summarize()</code></h2>
<p>Your colleagues have been talking lately about how the run has been getting earlier and earlier in recent years. To determine if their claims are correct, you decide to develop a method to find the day on which 50% of the run has passed (the median run date) and plot it over time. If there is a downward trend, then the run has been getting earlier. First, you need to define another function to find the day that corresponds to 50% of the run. If there were days when the cumulative run on that day equaled exactly 0.5, we could simply use <code>which()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ind =<span class="st"> </span><span class="kw">which</span>(dat<span class="op">$</span>cprun <span class="op">==</span><span class="st"> </span><span class="fl">0.5</span>)
dat<span class="op">$</span>jday[ind]</code></pre></div>
<p>The <code>which()</code> function is useful: it returns the indices (element places) <em>for which</em> the condition is <code>TRUE</code>. However, you need to do a workaround here, since the median day is likely not exactly 0.5, and it must be .5 in order for <code>==</code> to return a <code>TRUE</code>). You will give the function two vectors and it will look for a value that is closest to 0.5 in one vector and pull out the corresponding value in the second vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">find_median_doy =<span class="st"> </span><span class="cf">function</span>(p,doy) {
  ind =<span class="st"> </span><span class="kw">which.min</span>(<span class="kw">abs</span>(p <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span>))
  doy[ind]
}</code></pre></div>
<p>This function will take every element of <code>p</code>, subtract 0.5, take the absolute value of the results (make it positive, even if it is negative), and find the element number that is smallest. This will be the element with the value closest to 0.5. Note that you could find the first quartile (0.25) or third quartile (0.75) of the run by inserting these in for 0.5 above<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>. Try your function on the 2015 data only:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># use function</span>
med_doy15 =<span class="st"> </span><span class="kw">find_median_doy</span>(<span class="dt">p =</span> y15<span class="op">$</span>cprun, <span class="dt">doy =</span> y15<span class="op">$</span>doy)

<span class="co"># pull out the day it called the median to verify it works</span>
<span class="kw">filter</span>(y15, doy <span class="op">==</span><span class="st"> </span>med_doy15) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(cprun)</code></pre></div>
<pre><code>##       cprun
## 1 0.5023032</code></pre>
<p>The <code>select()</code> function in <code>{dplyr}</code> extracts the variables requested from the data frame. If there is a grouping variable set using <code>group_by()</code>, it will be returned as well. It looks like the function works. Now combine it with <code>summarize()</code> to calculate the median day for every year:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">med_doy =<span class="st"> </span>
<span class="st">  </span>dat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">doy =</span> <span class="kw">find_median_doy</span>(cprun, doy))
<span class="kw">head</span>(med_doy)</code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year     doy
##   &lt;fct&gt;  &lt;int&gt;
## 1 y_1917   184
## 2 y_1919   188
## 3 y_1921   179
## 4 y_1923   184
## 5 y_1925   182
## 6 y_1927   188</code></pre>
<p>Now, use your <code>{dplyr}</code> skills to turn the year column into a numeric variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># get years as a number</span>
med_doy<span class="op">$</span>year =<span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>(med_doy) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># extract only the year column</span>
<span class="st">  </span><span class="kw">select</span>(year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># turn it to a vector and extract unique values</span>
<span class="st">  </span>unlist <span class="op">%&gt;%</span><span class="st"> </span>unname <span class="op">%&gt;%</span><span class="st"> </span>unique <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># replace &quot;y_&quot; with nothing</span>
<span class="st">  </span><span class="kw">gsub</span>(<span class="dt">pattern =</span> <span class="st">&quot;y_&quot;</span>, <span class="dt">replacement =</span> <span class="st">&quot;&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># turn to a integer vector</span>
<span class="st">  </span>as.integer</code></pre></div>
<p>Now plot the median run dates as a time series:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(doy <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> med_doy, <span class="dt">pch =</span> <span class="dv">16</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-45-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It doesn’t appear that there is a trend in either direction, but fit a regression line because you can (Section <a href="ch3.html#regression">3.1.1</a>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit =<span class="st"> </span><span class="kw">lm</span>(doy <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> med_doy)
<span class="kw">summary</span>(fit)<span class="op">$</span>coef

<span class="kw">plot</span>(doy <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> med_doy, <span class="dt">pch =</span> <span class="dv">16</span>)
<span class="kw">abline</span>(fit, <span class="dt">lty =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>##                  Estimate  Std. Error    t value     Pr(&gt;|t|)
## (Intercept) 193.781416567 27.80436398  6.9694605 8.190067e-09
## year         -0.005138055  0.01414108 -0.3633424 7.179445e-01</code></pre>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-47-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The results tell you that there is a 0.005 day decrease in median run date for every 1 year that has gone by and that it is not significantly different from a zero day decrease per year. The statistical evidence does not support your colleagues’ speculations.</p>
</div>
<div id="fit-the-model" class="section level2">
<h2><span class="header-section-number">5.10</span> Fit the Model</h2>
<p>You have done some neat data exploration exercises (and hopefully learned <code>{dplyr}</code> and piping along the way!), but your ultimate task with this data set is to run a spawner-recruit analysis on all the data. A <strong>spawner-recruit analysis</strong> is one that links the number of total fish produced in a year (the recruits) to the total number of fish that produced them (the spawners). This is done in an attempt to describe the productivity and carrying capacity of the population and to obtain <strong>biological reference points</strong> off of which harvest policies can be set. You will need to summarize the daily data into annual totals of escapement and total run:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sr_dat =<span class="st"> </span>
<span class="st">  </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">S =</span> <span class="kw">sum</span>(esc, <span class="dt">na.rm =</span> T),
            <span class="dt">R =</span> <span class="kw">sum</span>(run, <span class="dt">na.rm =</span> T))

<span class="kw">head</span>(sr_dat)</code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   year       S       R
##   &lt;fct&gt;  &lt;int&gt;   &lt;dbl&gt;
## 1 y_1917  7031  20785.
## 2 y_1919 19647  43553.
## 3 y_1921 45106 113682.
## 4 y_1923 69160 196212.
## 5 y_1925 66306 171006.
## 6 y_1927 96622 243212.</code></pre>
<p>You didn’t need to use <code>group_by()</code> here because the data were still grouped from an earlier task. But, there is no harm in putting it in, and it would help make your code more readable if you were to include it.</p>
<p>That is the main data manipulation you need to do in order to run the spawner-recruit analysis. You can fit the model using <code>nls()</code> (Section <a href="ch3.html#nls">3.4</a>). The model you will fit is called a <strong>Ricker spawner-recruit model</strong> and has the form:</p>
<span class="math display" id="eq:ricker-ch5">\[\begin{equation}
  R_t = \alpha S_{t-1} e^{-\beta S_{t-1} + \varepsilon_t} ,\varepsilon_t \sim N(0,\sigma)
\tag{5.1}
\end{equation}\]</span>
<p>where <span class="math inline">\(\alpha\)</span> is a parameter representing the maximum recruits per spawner (obtained at very low spawner abundances) and <span class="math inline">\(\beta\)</span> is a measure of the strength of <strong>density-dependent mortality</strong>. Notice that the error term is in the exponent, which makes <span class="math inline">\(e^{\varepsilon_t}\)</span> lognormal. To get <code>nls()</code> to fit this properly, we will need to fit to <span class="math inline">\(log(R_t)\)</span> as the response variable. Write a function that will predict log recruitment from spawners given the two parameters (ignore the error term):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ricker =<span class="st"> </span><span class="cf">function</span>(S, alpha, beta) {
  <span class="kw">log</span>(alpha <span class="op">*</span><span class="st"> </span>S <span class="op">*</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>beta <span class="op">*</span><span class="st"> </span>S))
}</code></pre></div>
<p>Fit the model to the data using <code>nls()</code>. Before you fit it, however, you’ll need to do another lag. This is because the run that comes back in one year was spawned by the escapement the previous odd year (you only have odd years in the data). This time extract the appropriate years “by-hand” rather than using the <code>lag()</code> or <code>lead()</code> functions as before:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the number of years</span>
nyrs =<span class="st"> </span><span class="kw">nrow</span>(sr_dat)
<span class="co"># the spawners to fit to:</span>
S_fit =<span class="st"> </span>sr_dat<span class="op">$</span>S[<span class="dv">1</span><span class="op">:</span>(nyrs <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)]
<span class="co"># the recruits to fit to:</span>
R_fit =<span class="st"> </span>sr_dat<span class="op">$</span>R[<span class="dv">2</span><span class="op">:</span>nyrs]</code></pre></div>
<p>Fit the model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit =<span class="st"> </span><span class="kw">nls</span>(<span class="kw">log</span>(R_fit) <span class="op">~</span><span class="st"> </span><span class="kw">ricker</span>(S_fit, alpha, beta),
          <span class="dt">start =</span> <span class="kw">c</span>(<span class="dt">alpha =</span> <span class="dv">6</span>, <span class="dt">beta =</span> <span class="dv">0</span>))
<span class="kw">coef</span>(fit); <span class="kw">summary</span>(fit)<span class="op">$</span>sigma</code></pre></div>
<pre><code>##        alpha         beta 
## 5.341553e+00 6.896867e-06</code></pre>
<pre><code>## [1] 0.4047541</code></pre>
<p>Given that the true values for these data were: <span class="math inline">\(\alpha = 6\)</span>, <span class="math inline">\(\beta = 8\times10^{-6}\)</span>, and <span class="math inline">\(\sigma = 0.4\)</span>, these estimates look pretty good.</p>
<p>Plot the recruits versus spawners and the fitted line:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the S-R pairs</span>
<span class="kw">plot</span>(R_fit <span class="op">~</span><span class="st"> </span>S_fit, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">cex =</span> <span class="fl">1.5</span>,
     <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">max</span>(S_fit)), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">max</span>(R_fit)))
<span class="co"># extract the estimates</span>
ests =<span class="st"> </span><span class="kw">coef</span>(fit)
<span class="co"># obtain and draw on a fitted line</span>
S_line =<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="kw">max</span>(S_fit), <span class="dt">length =</span> <span class="dv">100</span>)
R_line =<span class="st"> </span><span class="kw">exp</span>(<span class="kw">ricker</span>(<span class="dt">S =</span> S_line,
                <span class="dt">alpha =</span> ests[<span class="st">&quot;alpha&quot;</span>],
                <span class="dt">beta =</span> ests[<span class="st">&quot;beta&quot;</span>]))
<span class="kw">lines</span>(R_line <span class="op">~</span><span class="st"> </span>S_line, <span class="dt">lwd =</span><span class="dv">3</span>)
<span class="co"># draw the 1:1 line</span>
<span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-53-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The diagonal line is the <strong>1:1 replacement line</strong>: where 1 spawner would produce 1 recruit. The distance between this line and the curve is the theoretical <strong>harvestable surplus</strong> available at each spawner abundance that would keep the stock at a fixed abundance. The biological reference points that might be used in harvest management are:</p>
<span class="math display" id="eq:ricker-brps">\[\begin{eqnarray*}
&amp;&amp; S_{MAX}=\frac{1}{\beta},\\
&amp;&amp; S_{eq}=log(\alpha) S_{MAX},\\
&amp;&amp; S_{MSY}=S_{eq} \left(0.5-0.07*log(\alpha)\right)
\tag{5.2}
\end{eqnarray*}\]</span>
<p>Where <span class="math inline">\(S_{MAX}\)</span> is the spawner abundance expected to produce the maximum recruits, <span class="math inline">\(S_{eq}\)</span> is the spawner abundance that should produce exactly replacement recruits, and <span class="math inline">\(S_{MSY}\)</span> is the spawner abundance that is expected to produce the maximum surplus (all under the assumption of no environmental variability). You can calculate the reference points given in Equation <a href="ch5.html#eq:ricker-brps">(5.2)</a> from your parameter estimates:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Smax =<span class="st"> </span><span class="dv">1</span><span class="op">/</span>ests[<span class="st">&quot;beta&quot;</span>]
Seq =<span class="st"> </span><span class="kw">log</span>(ests[<span class="st">&quot;alpha&quot;</span>]) <span class="op">*</span><span class="st"> </span>Smax
Smsy =<span class="st"> </span>Seq <span class="op">*</span><span class="st"> </span>(<span class="fl">0.5</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.07</span> <span class="op">*</span><span class="st"> </span><span class="kw">log</span>(ests[<span class="st">&quot;alpha&quot;</span>]))
brps =<span class="st"> </span><span class="kw">round</span>(<span class="kw">c</span>(<span class="dt">Smax =</span> <span class="kw">unname</span>(Smax),
               <span class="dt">Seq =</span> <span class="kw">unname</span>(Seq),
               <span class="dt">Smsy =</span> <span class="kw">unname</span>(Smsy)), <span class="op">-</span><span class="dv">3</span>)</code></pre></div>
<p>Draw these reference points onto your plot and label them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">abline</span>(<span class="dt">v =</span> brps, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)
<span class="kw">text</span>(<span class="dt">x =</span> brps, <span class="dt">y =</span> <span class="kw">max</span>(R_fit) <span class="op">*</span><span class="st"> </span><span class="fl">1.08</span>, 
     <span class="dt">labels =</span> <span class="kw">names</span>(brps), <span class="dt">xpd =</span> T, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="au-r-workshop_files/figure-html/unnamed-chunk-56-1.png" width="672" style="display: block; margin: auto;" /></p>
<hr />
</div>
<div id="exercise-5" class="section level2 unnumbered">
<h2>Exercise 5</h2>
<p>In this exercise, you will be working with another simulated salmon data set (from an age-structured population this time, like Chinook salmon <em>Oncorhynchus tshawytscha</em>). You have information on individual fish passing a <strong>weir</strong>. A weir is a blockade in a stream that biologists use to count fish as they pass through. Most of the day, the weir is closed and fish stack up waiting to pass. Then a couple times a day, biologists open a gate in the weir and count fish as they swim through. Each year, the biologists sample a subset of fish that pass to get age, sex, and length. There are concerns that by using large mesh gill nets, the fishery is selectively taking the larger fish and that this is causing a shift in the size-at-age, age composition, and sex composition. If this is the case, it could potentially mean a reduction in productivity since smaller fish have fewer eggs. You are tasked with analyzing these data to determine if these quantities have changed overtime. Note that documenting directional changes in these quantities over time and the co-occurrence of the use of large mesh gill nets does not imply causation.</p>
<p><em>The solutions to this exercise are found at the end of this book (<a href="exercise-solutions.html#ex5-answers">here</a>). You are <strong>strongly recommended</strong> to make a good attempt at completing this exercise on your own and only look at the solutions when you are truly stumped.</em></p>
<p>Use the data found in <code>asl.csv</code> (<strong>a</strong>ge, <strong>s</strong>ex, <strong>l</strong>ength) (see the <a href="index.html#data-sets">instructions</a> for details on acquiring the data files for this book). Create a new R script <code>Ex5.R</code> in your working directory. Open this script and read the data file into R. If this is a new session, load the <code>{dplyr}</code> package.</p>
<ol style="list-style-type: decimal">
<li>Count the number of females that were sampled each year using the <code>{dplyr}</code> function <code>n()</code> within a <code>summarize()</code> call (<em>Hint: <code>n()</code> works just like length - it counts the number of records</em>).</li>
<li>Calculate the proportion of females by year.</li>
<li>Plot percent females over time. Does it look like the sex composition has changed over time?</li>
<li>Calculate mean length by age, sex, and year.</li>
<li>Come up with a way to plot a time series of mean length-at-age for both sexes. Does it look like mean length-at-age has changed over time for either sex?</li>
</ol>
<hr />
<div id="exercise-5-bonus" class="section level3 unnumbered">
<h3>Exercise 5 Bonus</h3>
<ol style="list-style-type: decimal">
<li>Calculate the age composition by sex and year (what proportion of all the males in a year were age 4, age 5, age 6, age 7, and same for females).</li>
<li>Plot the time series of age composition by sex and year. Does it look like age composition has changed over time?</li>
</ol>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-reshape2">
<p>Wickham, Hadley. 2007. “Reshaping Data with the reshape Package.” <em>Journal of Statistical Software</em> 21 (12): 1–20. <a href="http://www.jstatsoft.org/v21/i12/" class="uri">http://www.jstatsoft.org/v21/i12/</a>.</p>
</div>
<div id="ref-R-dplyr">
<p>Wickham, Hadley, Romain Francois, Lionel Henry, and Kirill Müller. 2017. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr" class="uri">https://CRAN.R-project.org/package=dplyr</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>E.g., <code>&quot;hatch&quot;</code>, “<code>Hatch</code>”, and <code>&quot;HATCH&quot;</code> are all treated as different factor levels in R<a href="ch5.html#fnref1">↩</a></p></li>
<li id="fn2"><p>This is the fraction of all fish that came back each year that did so on or before a given day<a href="ch5.html#fnref2">↩</a></p></li>
<li id="fn3"><p>It doesn’t look like much, but this information is incredibly important for fishery managers. It provides information on how much of the annual run has passed on each day. You can see that the rate of change is the fastest in the middle of the run, this corresponds to the major hump in the plots you made earlier (which were raw numbers by day). Of course during the run, the managers don’t know what proportion of the total run has passed because they don’t know the total number of fish that will come that season, but by characterizing the mean and variability of the different run completion proportions on each day in the past, they can have some idea of how much of the run to expect yet to come on any given day.<a href="ch5.html#fnref3">↩</a></p></li>
<li id="fn4"><p>This is the perfect kind of thing to make an argument for in your function!<a href="ch5.html#fnref4">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["au-r-workshop.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
